### ISSUE TITLE
WEB UI not displaying settings correctly 

### ISSUE THREAD

**Issue by ballzac81** [guydavis/machinaris#10]
The WEB UI in portrait mode does not show settings but it when you turn the phone into landscape they show up

![Screenshot_20210516-100019_Edge](https://user-images.githubusercontent.com/84253792/118381430-1b6fe180-b62e-11eb-928e-dff06e82c48b.jpg)
![Screenshot_20210516-100034_Edge](https://user-images.githubusercontent.com/84253792/118381432-1ca10e80-b62e-11eb-83bc-3fec26fe4467.jpg)

**Comment by guydavis** [comment]
Stumbled across the solution to this.  Available in the next release: 

![image](https://user-images.githubusercontent.com/12936/133716708-4abb9987-3831-4436-944e-11c65457abf0.png)

**Comment by guydavis** [comment]
Closing as now available in [released v0.5.6](https://github.com/guydavis/machinaris/releases/tag/0.5.6) version.  Great catch!
