### ISSUE TITLE
v0.4.0 - Fullnode/Controller shows higher "Expected Time to Win", not considering harvester plots

### ISSUE THREAD

**Issue by guydavis** [guydavis/machinaris#118]
Currently, the fullnode only reports an ETW  for only its own local plots, not a proper lower ETW which considers all harvesters'  plots too.

Notes: 

- Each harvester is answering challenges for their plots, but `chia farm summary` on the harvester simply shows 'Unknown' so it's not considered by Machinaris for the overall Summary view.  
- Machinaris Summary view does report the correct total number of plots and total plot size, including Harvesters.

TODO: Figure a way to calculate ETW from total plot count across all farmers/harvesters, that doesn't rely on `chia farm summary` of the fullnode.

**Comment by AndersStruck** [comment]
This is the default operating node of the official chia full node as well.

**Comment by guydavis** [comment]
This regressed when updating to the latest branch of Chia binaries to prepare for official pooling.  Thanks @sparklyballs for the issue report.  Should be fixed in very next test release.

**Comment by guydavis** [comment]
Closing as [v0.5.0](https://github.com/guydavis/machinaris/discussions/159) is now released.
