### ISSUE TITLE
adding last attempted proof to UI

### ISSUE THREAD

**Issue by ballzac81** [guydavis/machinaris#12]
is it easy to add like the last attempted proof to the UI front page so you can see your node trying to win that XCH
![last attempted proof](https://user-images.githubusercontent.com/84253792/118383506-ac03ed00-b641-11eb-87cc-6f50517c3efe.jpg)

**Comment by Hukuma1** [comment]
+1! Yes please. Would really help to show that Machinaris is trying to find the Chia ;)

![machmockup](https://user-images.githubusercontent.com/54511555/119241833-4797d080-bb0e-11eb-855f-bc26189481fc.png)

This way you won't need to go to any other screen to see if it's working too.

**Comment by dfarin** [comment]
Sounds great, its realy nice to watch.
I would suggest to add additional information.
Normaly i look how often the filter passed and then i search the debug.log for the needed time.
Since i read that it must not take longer then 30 seconds to "proof" it´s important to know this.
"0 plots were eligible for farming 5b0f23431b... Found 0 proofs. **Time: 0.01799** s. Total 146 plots"
![image](https://user-images.githubusercontent.com/9096265/119276037-d1cc5b80-bc18-11eb-8771-3715bd32f13c.png)

**Comment by Hukuma1** [comment]
Good point! Yeah I hope that info (especially if higher than 30 seconds :( ) also shows up in alerts/log area so we can pinpoint problems.

**Comment by guydavis** [comment]
Like this? Parsing debug.log doesn't give the full challenge ID just a prefix...

![image](https://user-images.githubusercontent.com/12936/119279950-0118a380-bbec-11eb-9962-a83c7ffdbe88.png)

Since this is summary page, just the last 5 most recent in the log alright?

**Comment by guydavis** [comment]
Thanks for the great suggestion.  This is now available in the test image at `ghcr.io/guydavis/machinaris:test`.  Will be released to mainline in coming week.

**Comment by guydavis** [comment]
![image](https://user-images.githubusercontent.com/12936/119394253-33c7a800-bc8f-11eb-8a7d-bef9906c9e8e.png)

Re-opening as having a more frequent update (~5-10 secs) of just the challenge table would be nice to have.  Will probably have to wait for a refactor in the future around more XHR subview calls though.

**Comment by cr8tor456** [comment]
This is awesome, came to add comments but it seems this is already in progress.
Great work, i thank you many times over.

**Comment by guydavis** [comment]
Latest test release now performs XHR refresh every 8 seconds so the Challenges table updates quite frequently now.  Should hit release by next week.  

![image](https://user-images.githubusercontent.com/12936/122322269-73765e00-cee2-11eb-8faf-bd1e49c7fec1.png)
