### ISSUE TITLE
show free space available when plotting

### ISSUE THREAD

**Issue by technickal1** [guydavis/machinaris#120]
[on Linux] often I find myself checking free space since I run on so many drives with `df -h | grep chia` 

it would be nice to see available space on the current drive in the plotting window for that drive. I'm not keen on adding another column, but if we can't add the amount of free space available, have alerts sent or madmax automatically stop when disk space is not there to use.

**Comment by guydavis** [comment]
Available in test release.  Shows current disk usage per plotting drive.  Will be available soon in full release.

**Comment by guydavis** [comment]
Now available in v0.5.3+
