### ISSUE TITLE
/bin/sh: 1: cannot open /dev/tty: No such device or address

### ISSUE THREAD

**Issue by Aerya** [guydavis/machinaris#13]
Hi,

Building/running on Ubuntu I got this error. Any advise?

Logs are clean

```
Chia directory /root/.chia/mainnet
/root/.chia/mainnet already exists, no migration action taken
to use your own keys pass them as a text file -v /path/to/keyfile:/path/in/container and -e keys="/path/in/container"
Generating private key
Added private key with public key fingerprint xxx
Plots directory appears to be empty and you have not specified another, try mounting a plot directory with the docker -v command 
Added plot directory "/plots".
Daemon not started yet
Starting daemon
chia_farmer: started
Configuring Chia...
Configuring Plotman...
Starting Machinaris...
Completed container startup.  Browse to port 8926.

```

**Comment by guydavis** [comment]
Good day, add `-t` for an Extra Parameter.  Please see the [install guide for Unraid](https://github.com/guydavis/machinaris/wiki/Unraid).  If you're doing straight Docker, then add `-t` to the run command.  Please let me know if this helps.

**Comment by Aerya** [comment]
Thanks, I could test out your WUI. Nice working even if not yet ready/secured for dedicated/virtual servers.
May I suggest you some features?
