### ISSUE TITLE
[FR] Add last 24 hour summary to Summary page

### ISSUE THREAD

**Issue by Hukuma1** [guydavis/machinaris#130]
How about the same little skinny block like `Expected Time to Win` that is at the very top, we add a `24 Hour Summary:` at the bottom (right above the version text)? Or maybe even right below the expected time to win section? Same small footprint ideally (not new line for every item like in `Alerts` page)

The same info from the `Alerts` page, but just showing the last 24 hours. This way your one-stop visit for last 24 hours will be the `Summary` page for quick glancing of all info.

**Comment by guydavis** [comment]
Sorry, I've been busy around official Chia pool support.  This is a great idea.  I'll try to get this going soon!

**Comment by guydavis** [comment]
Hi, I've taken a run at displaying the change over the past day on the Summary page.  Please provide your feedback: 

![20210723_163219](https://user-images.githubusercontent.com/12936/126875867-fbf1cfdd-da87-4ed4-8544-37a16ccb4629.png)

**Comment by Hukuma1** [comment]
On first glance it looks very busy. I appreciate some of the padding and empty space of the current design. But if it's a choice between the two of these, I'd still choose the newer one since it does have all the info right on front screen. Good job!

**Comment by toto99303** [comment]
Looks nice to me, too. Great job!
Is there any way to also have the "Points found in the last 24 hours" and "Points successful in the last 24 hours" much like in the official GUI?

**Comment by guydavis** [comment]
@toto99303 Good suggestion!  Try the latest `:test` [image](https://github.com/guydavis/machinaris/wiki/Releases#release-streams):

![image](https://user-images.githubusercontent.com/12936/127594762-4c288746-5e08-4877-a3cd-042ce6372689.png)

**Comment by toto99303** [comment]
Thanks! I forced upgrade on the :test image, but there's no Pooling tab on the left. Manyally browsing it also returns non existing page. Am I doing something wrong?

**Comment by guydavis** [comment]
Hi, test release is still building. Adding arm64 support recently pushed builds from 10 mins to well over 2 hours. Sorry!

https://github.com/guydavis/machinaris/actions/runs/1080884043

**Comment by toto99303** [comment]
Now it's fine. Thanks again for doing all this!!

**Comment by toto99303** [comment]
How are points for last 24 hours calculated? Is this value coming from the pool, or it's calculated locally? It looks like my values are wrong. For every 100 k32 plots we should have roughly 1000 points for 24 hours. I have 997 plots currently, but points for the last 24 hours are way lower than 9000.

![Screenshot_20210801-193713_Chrome](https://user-images.githubusercontent.com/20519170/127778677-d0057ec8-4b4a-40d0-bd89-b7dcd1520d48.jpg)

**Comment by guydavis** [comment]
Interesting.  Machinaris is simply calling the [Chia RPC endpoint for pool state](https://github.com/Chia-Network/chia-blockchain/blob/main/chia/rpc/farmer_rpc_api.py#L20) and returning the values it provides.  

Thanks for the feedback on the `:test` version of Machinaris.  I'll see what others report too.

**Comment by toto99303** [comment]
I am not proficient in Java, but It looks like they calculate the 24 hour points in the GUI here:

https://github.com/Chia-Network/chia-blockchain-gui/blob/d697b48f9a1324672802fd9e6fd93b079cc0f063/src/components/plotNFT/PlotNFTCard.tsx#L104

**Comment by guydavis** [comment]
I'm not seeing any other reports related to this in latest versions of Machinaris.  If this concern about points is still an issue for you, please open a new issue, with all the specifics listed.  I'm going to close out this original issue from late June.
