### ISSUE TITLE
Clear alerts from the alerts view

### ISSUE THREAD

**Issue by sparklyballs** [guydavis/machinaris#142]
Would be handy at times to be able to clear the alerts tab, as it can get full of messages about disconnecting etc when i'm making changes to remote nodes.

**Comment by guydavis** [comment]
Good suggestion!  Just added ability to select one or more Alerts to remove from display.

**Comment by guydavis** [comment]
Now available in [v0.5.1 release](https://github.com/guydavis/machinaris/releases/tag/0.5.1).
