### ISSUE TITLE
Support for Raspberry Pi 64 bit (aarch64)

### ISSUE THREAD

**Issue by lestd** [guydavis/machinaris#155]
The Linux containers don't seem to support aarch64 on my Raspberry Pi 4 full node (Raspbian 64)

Linux raspberrypi 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux

root@raspberrypi:/ # docker logs machinaris
standard_init_linux.go:207: exec user process caused "exec format error"

Thanks!

**Comment by raspi-ninja** [comment]
I wanted to setup my NanoPi M4 board as a harvester and had the same issue.  I got it working by 
building docker image on the device. Essentially building it for an aarch64.

- clone the git repo
- edit and comment chia-plotter builds in the dockerfile (since they failed to build on my device)
- run `docker build .`
- run the docker container with the new image 
- put fake chia-plotter file in the bin folder because the webapp & api fails to load if it can't find it

i still ran into some weird issues but now it's running fine. Sorry for the vague details but hope it puts you on the right track.

**Comment by elexx** [comment]
I tried cross-building the image for aarch64 with
```
docker buildx build --progress plain --platform linux/arm64 --build-arg CHIA_BRANCH=1.2.2 --build-arg FLAX_BRANCH=main .
```
but ran into:
```
#5 271.1 Errors were encountered while processing:
#5 271.1  libc-bin
#5 271.2 E: Sub-process /usr/bin/dpkg returned an error code (1)
#5 ERROR: executor failed running [/bin/sh -c apt-get update 	&& apt-get install -y 		acl 		apt 		bash 		bc 		build-essential 		ca-certificates 		curl 		git 		jq 		nfs-common 		openssl 		python3 		python3.9-distutils 		python3.9-venv 		python3-dev 		python3-pip 		python-is-python3 		sqlite3 	sudo 		tar 		tzdata 		unzip 		vim 		wget 		cmake 		rsync 		libsodium-dev 		iputils-ping 			&& rm -rf 		/tmp/* 		/var/lib/apt/lists/* 		/var/tmp/*]: exit code: 100
------
 > [package_stage 2/2] RUN 	apt-get update 	&& apt-get install -y 		acl 		apt 		bash 		bc 		build-essential 		ca-certificates 		curl 		git 		jq 		nfs-common 		openssl 		python3 		python3.9-distutils 		python3.9-venv 		python3-dev 		python3-pip 		python-is-python3 		sqlite3 	sudo 		tar 		tzdata 		unzip 		vim 		wget 		cmake 		rsync 		libsodium-dev 		iputils-ping 			&& rm -rf 		/tmp/* 		/var/lib/apt/lists/* 		/var/tmp/*:
------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c apt-get update 	&& apt-get install -y 		acl 		apt 		bash 		bc 		build-essential 		ca-certificates 		curl 		git 		jq 		nfs-common 		openssl 		python3 	python3.9-distutils 		python3.9-venv 		python3-dev 		python3-pip 	python-is-python3 		sqlite3 		sudo 		tar 		tzdataunzip 		vim 		wget 		cmake 		rsync 		libsodium-dev iputils-ping 			&& rm -rf 		/tmp/* 		/var/lib/apt/lists/* 	/var/tmp/*]: exit code: 100
```

Any ides if this is just a problem wenn cross-building or did you have the same problem, when building directly on your NanoPi M4, @raspi-ninja?

**Comment by guydavis** [comment]
Hi! For those with Raspberry Pi 64-bit systems, please give the latest `ghcr.io/guydavis/machinaris:develop` image a try.  As of [latest build](https://github.com/guydavis/machinaris/actions/runs/1062761040), the `arm64` architecture is enabled, but I don't have any hardware to try running it.  Here's the details on [GHCR ](https://github.com/guydavis/machinaris/pkgs/container/machinaris)and [DockerHub](https://hub.docker.com/layers/guydavis/machinaris/develop/images/sha256-183c192c87258c67fb64d8491f5d83646bb323ae9310bed3b7b42e5633dd213f?context=repo).

In particular, you'll need an existing Machinaris controller running on another PC, as it really only makes sense to launch a [Machinaris worker](https://github.com/guydavis/machinaris/wiki/Workers#harvester) (`mode=harvester`) on the RaspPi I think. Please let me know how things go.  In particular, please [provide the logs](https://github.com/guydavis/machinaris/wiki/Troubleshooting#nothing-works--where-are-the-logs).  Thanks!

**Comment by guydavis** [comment]
Heard from a user on Discord that this is working well for his RaspberryPi.  Will ensure this becomes part of regular build process.

**Comment by guydavis** [comment]
Closing as released in [v0.5.2](https://github.com/guydavis/machinaris/releases/tag/0.5.2) now.

**Comment by SquareMesh** [comment]
Hi @guydavis ,
Just tried fresh install of docker image in Raspberry Pi 4 using .yml from docker app.  
Initially got error (using :latest in yml) .. which brought me to this issue

pi@raspberrypi:~/machinaris $ sudo docker-compose up -d --force-recreate
Pulling machinaris (ghcr.io/guydavis/machinaris:latest)...
latest: Pulling from guydavis/machinaris
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

Then changed to :develop, which allowed me to create image, however docker container doesn't run and is showing the following message..

pi@raspberrypi:~/machinaris/machinaris/docker $ sudo docker logs machinaris
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error

Apologies for tagging against older closed issue, let me know if you would like a new issue raised?

**Comment by guydavis** [comment]
Hi, sorry.  Sounds like you are trying to run with a 32-bit RaspPiOS version.  This isn't supported by [Machinaris](https://github.com/guydavis/machinaris/wiki/RaspberryPiOS) or by [Chia](https://github.com/guydavis/machinaris/wiki/RaspberryPiOS).  Please try to switch to a 64-bit OS if you can. 

As for the `:develop` images, they support `x86_64` only for speed of build time.  They won't run on any RaspPi device, so please stick with the `:latest` images which is the [latest official release](https://github.com/guydavis/machinaris/wiki/Releases#release-streams).

**Comment by SquareMesh** [comment]
Hi @guydavis ,
Sorry, meant to check earlier and forgot, yeah you are correct, I'm using 32bit OS.. I had assumed the new download was 64 bit, my mistake.  Thanks for prompt reply.

**Comment by SquareMesh** [comment]
Hi @guydavis , just a follow up to say it is all working after install 64bit OS.  Thanks for your help.
