### ISSUE TITLE
Better support for multiple wallets

### ISSUE THREAD

**Issue by Woogz-git** [guydavis/machinaris#172]
**Describe the request**
Machinaris supports adding multiple mnemonic files into the config but doesn't have any capability for selecting which wallet to work with when running commands such as joining pools.

This results in having to temporarily remove the mnemonic you don't want to work with when making changes. Additionally it results in the tool not being able to sync the secondary wallet.

You are able to copy in sync files from another client for your secondary wallet but even after doing so it will not show you both wallets in the wallets tab despite both fingerprints showing in the keys tab.

**Images**
<img width="251" alt="chia wallet show cli" src="https://user-images.githubusercontent.com/21038356/125300516-1b235800-e2f8-11eb-9b75-6a7f8f32a4fd.png">

<img width="1417" alt="chia wallet show gui" src="https://user-images.githubusercontent.com/21038356/125300589-2f675500-e2f8-11eb-8274-d044337125e8.png">

<img width="821" alt="chia keys show" src="https://user-images.githubusercontent.com/21038356/125300041-abad6880-e2f7-11eb-86de-ca2cfa911470.png">

<img width="1111" alt="Screen_Shot_2021-07-11_at_11 41 44_PM" src="https://user-images.githubusercontent.com/21038356/125296346-312f1980-e2f4-11eb-96ce-9a02b762e215.png">

**Additional comments**

**Comment by Yamanipanuchi** [comment]
So my system will not even show my pool wallets at all. Haven't been able to figure out why. Pool wallets show up fine on my windows machines with the same Key.

**Comment by AndyRPH** [comment]
All my pools are telling me I've reported nothing since switching to machinaris.  Which logs in particular would be helpful?  Both my MacBooks are setup as full nodes, but both report issues communicating with the harvester?  Shouldn't that be reallly unlikely using machinaris as a full node?

**Comment by guydavis** [comment]
> All my pools are telling me I've reported nothing since switching to machinaris. Which logs in particular would be helpful? Both my MacBooks are setup as full nodes, but both report issues communicating with the harvester? Shouldn't that be reallly unlikely using machinaris as a full node?

Hi!  I would recommend only a single Machinaris [controller/fullnode](https://github.com/guydavis/machinaris/wiki/Workers) on your LAN.  Not sure how well two will work if they are both port-forwarded to your router.  The benefit of a single controller is a single WebUI to control your entire farm.

Once you have a single Machinaris fullnode/controller, visit the Workers page, click the New button to generate a Docker run/compose for your harvesters and/or plotters.  For [harvesters](https://github.com/guydavis/machinaris/wiki/Workers#harvester), don't forget to manually copy the SSL certs over from your fullnode.

To troubleshoot issues, check the Workers page on the fullnode.  Also check the [logs ](https://github.com/guydavis/machinaris/wiki/Troubleshooting)on the harvester, particularly at ~/.machinaris/mainet/log/debug.log.  Finally, ensure that port tcp/8447 is reachable on your controller as that is required for the harvester to connect.  

![image](https://user-images.githubusercontent.com/12936/126924416-3677d0fe-0b01-483e-a922-428bcc98b2a8.png)

**Comment by guydavis** [comment]
Closing as this has been improved with latest version [v0.5.2](https://github.com/guydavis/machinaris/releases/tag/0.5.2).  Thanks for the feedback!
