### ISSUE TITLE
Points balance is incorrect for my 2nd pool.

### ISSUE THREAD

**Issue by ray-su** [guydavis/machinaris#188]
**Describe the bug**
I joined 2 pools. The Points balance number is wrong for my 2nd pool. However, I can confirm the Launcher ID is correct.

**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Add more than one pools

**System setup:**
 - Unraid
 - Docker 20.10.5 

**Additional context & screenshots**

**Comment by guydavis** [comment]
Please provide detailed screenshots showing both the Machinaris WebUI pages and the corresponding `chia plotnft` CLI commands you feel are not in alignment.  Thanks!

**Comment by ray-su** [comment]
I just checked with chia CLI, the information is align with Machinaris Web UI. I think this is a Chia bug then.

**Comment by guydavis** [comment]
Great.  Update here if you find the underlying cause.  Closing this Machinaris ticket for now.
