### ISSUE TITLE
Old pool_contract_address is being display in plotman.yaml editor after changing to a new address

### ISSUE THREAD

**Issue by ray-su** [guydavis/machinaris#189]
**Describe the bug**
I joined 2 pools, so I have 2 pool contract addresses. After changing from my 1st pool contract address to my 2nd one in Settings -> Plotting, then a "saved successfully" message is shown. However, after that, the editor is still showing my 1st contract address.  I went into the file system and open the plotman.yaml in my own text editor to verify, I do see that the current contract address  is my 2nd one. Please see screen shots below.

**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Join more than one pool
2. go Settings-> Plotting. Change plotman.yaml's pool_contract_address to your first 1st pool contract address and click Save
3. Change plotman.yaml's pool_contract_address from your 1st contract address to your 2nd pool's contract address and click Save
4. "Saved  successfully" message is shown,  but pool_contract_address will revert back to the 1st one
5. Go to your file system and find plotman.yaml and open it in a text editor,  you will see the pool_contract_address is actually the 2nd one

 

**System setup:**
 - Unraid
 - Docker 20.10.5
 - Machinaris branch: main
 - 0.5.0

**Config**
<details><summary>full configuration</summary>

```
# paste your Docker run or Docker compose here
```

</details>

**Additional context & screenshots**

<img width="1062" alt="Screen Shot 2021-07-16 at 12 15 10 PM" src="https://user-images.githubusercontent.com/14828286/125980272-e603fc3c-4df3-4c91-a2f5-8535b0f8237d.png">
<img width="874" alt="Screen Shot 2021-07-16 at 12 18 11 PM" src="https://user-images.githubusercontent.com/14828286/125980284-a4cb1bbd-f746-40cb-ad63-6b4b98f72aee.png">

**Comment by ray-su** [comment]
Forgot to mention,  other settings do show up correctly after editing,  only pool_contract_address has this weird behavior.

**Comment by guydavis** [comment]
Thanks for the report.  You are an exceptional case as you have two different PlotNFTs pointed to two different Chia pools. 

Machinaris is designed for majority of users who have a simple setup, a single PlotNFT and one pool.  In that case, the pool_contract_address of the first and only PlotNFT is displayed in Settings | Plotting for users to review and save.  This simplifies things for vast majority of users.

I've added guard to not bother trying to update display of pool_contract_address when multiple plotnfts are encountered.  User must do that manually for this more complicated config scenario.  Available in next release.

**Comment by guydavis** [comment]
Now available in [v0.5.1 release](https://github.com/guydavis/machinaris/releases/tag/0.5.1).
