### ISSUE TITLE
keys variable not being read properly

### ISSUE THREAD

**Issue by Mearman** [guydavis/machinaris#19]
Even though `No such file or directory: '/root/.chia/mnemonic.txt'`
I assumed there was something wrong with the entrypoint script, but I can't see anything amiss. 
https://github.com/guydavis/machinaris/blob/a5e3565ef1ef3f07877fef05173d66ec33a76048/entrypoint.sh#L22

**Comment by guydavis** [comment]
Hi, thanks for the comment.  Please try the latest development (`ghcr.io/guydavis/machinaris:develop`) build for a fresh setup.  I have improved the way keys are handled, now allowing multiple and offering to generate through WebUI if none found.  Looking for feedback on this enhancement.  Thanks again!

**Comment by Mearman** [comment]
seems to have done the trick

**Comment by Timi7007** [comment]
Your suggestion worked, but now my old 24-word isn't imported correctly as the chia client demands the following:
```
 No online backup file found, 
 Press S to skip restore from backup 
 Press F to use your own backup file: Exception from 'wallet' EOF when reading a line
```
This isn't manageable in the webinterface (yet) and the CLI is long past this point. Shall I open a separate issue?

**Comment by guydavis** [comment]
Great. Glad to hear that v0.2 helped with these issues.  Thanks for the feedback!
