### ISSUE TITLE
Missing Plots in machinaris

### ISSUE THREAD

**Issue by robertbigk** [guydavis/machinaris#194]
Hi, I use the Unraid Threadripper system, machinaris in docker.

I use an extra folder (hdd) to add plots.

I my main folder I got 198 plots in extra HDD 30.
When i check plots I got all extra folder and system show valid 228 plots
![msedge_Mf6jXyH5PK](https://user-images.githubusercontent.com/34956477/126051633-4c8d06d1-6545-45a9-9bac-401d90aabe7c.png)

But on the farming page, I got 228 plots in Farming:228 but only shows 198 from main directory in list.
![msedge_OMXPZ8M8Un](https://user-images.githubusercontent.com/34956477/126051655-ef8280ac-aed7-4527-a4d0-dddceeafb1bb.png)

![msedge_zkVsOctByo](https://user-images.githubusercontent.com/34956477/126051658-5ef8d21f-48a7-4653-9b6a-cb7bcea491c8.png)

In Space Pool also low number  I know is only estimated but before I 150 pools after an hour or two if change for 155
space spool show correct or very close and updated size very often but now estimated number all days show incorrect number even don't close to real numbers if that because part pools in other map folders?

![msedge_Op6JtHC5FV](https://user-images.githubusercontent.com/34956477/126051692-1ff88a3c-9aa8-4833-86e7-a9dce3f1e187.png)

**Comment by robertbigk** [comment]
When I check plots in farming tam his validates the actual count of plots and shows all ok. But in the log, I got an error not folder find?

![msedge_EvwGGHwkEw](https://user-images.githubusercontent.com/34956477/126051951-37710380-4a54-46d5-8b13-50792665834e.png)


My actual config
![msedge_X8Ll74Ch4M](https://user-images.githubusercontent.com/34956477/126052021-2fb9d9ec-2dc0-46cc-9308-b50535bc399d.png)

Is bug or do I miss something?

**Comment by robertbigk** [comment]
For more info i send rest screen 
![msedge_ko9JNuy3GI](https://user-images.githubusercontent.com/34956477/126052056-056319d8-8cce-4ad6-b8af-9d8b685d9a20.png)
![msedge_cWuMht7D00](https://user-images.githubusercontent.com/34956477/126052057-bcf55528-5a11-4923-9838-60718191c503.png)
![msedge_a5t4Nn78OI](https://user-images.githubusercontent.com/34956477/126052058-365790a0-a65d-47e0-9062-767ceb9958f4.png)
![msedge_oZPvSxhEoM](https://user-images.githubusercontent.com/34956477/126052059-c1abd70d-e0ec-4d1f-af9a-9f57dc189393.png)
![msedge_Jrdg39tqc5](https://user-images.githubusercontent.com/34956477/126052063-00ece857-87b7-4a57-be66-89bee32f92e3.png)

**Comment by robertbigk** [comment]
The last thing I plotting for xch2 and xch3 and all look ok and plot by added to the summary page.

![msedge_5nsvkoxTyg](https://user-images.githubusercontent.com/34956477/126052089-97c95088-5135-45f8-ab9b-97cda28e29c8.png)

**Comment by robertbigk** [comment]
ok next problem xch3 plot hdd not add plots from there 
Xch3 mapped in machinaris 
![msedge_5zjE3erlz8](https://user-images.githubusercontent.com/34956477/126080036-1235495b-2031-418e-ad5e-08ef633e163f.png)

![msedge_EvwGGHwkEw](https://user-images.githubusercontent.com/34956477/126080044-5d5ba6ab-fae7-4023-9fdd-d3079a5694c2.png)

in log shows xch3 and plotting add to the folder but no add to farming

**Comment by guydavis** [comment]
Good day!  Just back in town after being offline all weekend.  Thanks for the screenshots.  Please do the following to clean up your Chia/Flax paths from previous runs with old `plots_dir` variables:

```
chia plots remove -d /plots
flax plots remove -d /plots
chia plots remove -d /mnt/disks/xch1
flax plots remove -d /mnt/disks/xch1
```

This will not affect the plots themselves, just which folders will be searched by Chia and Flax binaries for farming.  The cleanup is necessary as neither of the folders above hold plots directly.

This assumes your `plots_dir`  (**not the singular `plot_dir` typo I see above**) has value: 

```
/plots/xch1:/plots/xch2:/plots/xch3
```

Hope this  helps!

**Comment by robertbigk** [comment]
I already fix the issue all work fine:) madmax ramdisk and add hdd .  Do You plan add another coin on what currently work on chia blockchain ? 

/plots/xch1:/plots/xch2:/plots/xch3 i have write that scheme and not work all for me i change for /plots/xch1/xch2/xch3... and all start work:)
