### ISSUE TITLE
Add build-in auth so as to prevent newbies to publish WUI port to the WWW

### ISSUE THREAD

**Issue by Aerya** [guydavis/machinaris#20]

**Comment by guydavis** [comment]
Good suggestion.  The challenge of implementing an authentication mechanism in the web-application itself is that it likely won't integrate well with all the ways that people will try to deploy Machinaris.  So, I think it's better to leave the infrastructure concerns such as [proxying](https://github.com/guydavis/machinaris/wiki/Nginx) and [authentication](https://github.com/guydavis/machinaris/wiki/FAQ#why-doesnt-machinaris-offer-an-authentication-mechanism-to-allow-logins) to more established platforms, ensuring wider integration.  Thanks for the feedback!
