### ISSUE TITLE
Add a dedicated Docker volume for CHIA storage for farming (best use: HDD)

### ISSUE THREAD

**Issue by Aerya** [guydavis/machinaris#21]

**Comment by guydavis** [comment]
Hi! Yes, Machinaris takes a `plots_dir` environment variable which is a colon-separated list of host volumes mounted in the container, each containg Chia plots.  Check out this [guide](https://github.com/guydavis/machinaris/wiki/FAQ#can-i-use-two-or-more-final-destination-directories-to-hold-my-plots) for more details.
