### ISSUE TITLE
Conf.: add a Download button to backup configs/mnemonic elsewhere on a local/remote/backup storage

### ISSUE THREAD

**Issue by Aerya** [guydavis/machinaris#22]

**Comment by guydavis** [comment]
Great suggestion!

**Comment by guydavis** [comment]
Latest test version now has a download button for Configs (yamls) as shown.  Should hit release by next week.

![image](https://user-images.githubusercontent.com/12936/122322131-34480d00-cee2-11eb-8cc0-8bbcdee9e331.png)
