### ISSUE TITLE
Machinaris theme(s)

### ISSUE THREAD

**Issue by Hukuma1** [guydavis/machinaris#24]
Not a coder, so not sure how to do a PR. But wanted to share some theme adjustments. Default Machinaris looks a bit of a mix between light and dark mode, so I wanted to just darken the background.

![machtheme1](https://user-images.githubusercontent.com/54511555/118740844-b1a83100-b801-11eb-9db1-4af2a4772d31.png)

```
<style> 
/* Main background color */
body {
  background-color: #15171a
}

/* Rounded sections */
.rounded-3 {
  border-radius: .5rem!important;
  background-color: #212529!important;
  -webkit-box-shadow: 0px 1px 0px 0px #000;
  box-shadow: 0px 1px 0px 0px #000;
  border: 0!important;
}

.text-success {
  color: #3aac59!important;
  font-weight: 500;
}

.display-6 {
  color: #c7c7c7;
}

/* Menu */
.col-auto.col-md-3.col-xl-2.px-sm-2.px-0.bg-dark {
  border-right: 1px solid #000;
}
</style>
```

Here is a default Chia GUI look (at least how it seems to look on Windows). Dark Mode:
![machtheme2](https://user-images.githubusercontent.com/54511555/118741023-28452e80-b802-11eb-9c97-bd481c96ed85.png)

```
<style> 
/* Main background color */
body {
  background-color: #303030
}

/* Rounded sections */
.rounded-3 {
  border-radius: .5rem!important;
  border: 0!important;
  -webkit-box-shadow: 0px 1px 0px 0px #000;
  box-shadow: 0px 1px 0px 0px #000;
  background-color: #424242!important;
}

.text-success {
  color: #3aac59!important;
  font-weight: 500;
}

.display-6 {
  color: #c7c7c7
}

/* Menu */
li .text-success {
  color: #fff!important;
}

.fs-4.bi-flower1 {
  color: #3aac59;
}

.fs-5.d-none.d-sm-inline {
  color: #3aac59;
}

.bg-dark {
  background-color: #424242!important;
}
</style>
```

And here is the light version:
![machtheme3](https://user-images.githubusercontent.com/54511555/118741132-6d696080-b802-11eb-94d5-dd4c44f4a0d7.png)

```
<style> 
/* Main background color */
body {
  background: linear-gradient(45deg, #ffffff 30%, #fdfdfd 90%);
}

/* Rounded sections */
.rounded-3 {
  border-radius: .5rem!important;
  background-color: #fff!important;
  -webkit-box-shadow: 0px 1px 0px 0px #9e9e9e;
  box-shadow: 0px 1px 0px 0px #9e9e9e;
  border: 1px solid #ddd;
  important;
}

.text-success {
  color: #3aac59!important;
  font-weight: 500;
}

.display-6 {
  color: #757575;
}

/* Menu */
.col-auto.col-md-3.col-xl-2.px-sm-2.px-0.bg-dark {
  border-right: 1px solid #ddd;
}

li .text-success {
  color: #757575!important;
}

.fs-4.bi-flower1 {
  color: #3aac59;
}

.fs-5.d-none.d-sm-inline {
  color: #3aac59;
}

.bg-dark {
  background-color: #fff!important;
}

i.fs-4.bi-github {
  color: #757575!important;
}

.ms-1.d-none.d-sm-inline {
  color: #757575!important;
}
</style>
```

I'm sure I messed up some classes I've targeted or someone can do a better job, but this is a quick copy/paste to get those colors for now. Hopefully a theme toggle could be made and we could drop these in to customize.

**Comment by guydavis** [comment]
This is awesome!  I've include your dark-mode improvements into Machinaris v0.2.1.  I'll get your light-mode integrated in a future release with a toggle in UI.  Great contribution.

**Comment by guydavis** [comment]
@antdragone Here's another interesting one for the frontend.  Found a [good article](https://github.com/vinorodrigues/bootstrap-dark-5) on using Bootstrap 5 for light/dark toggling.  Might be a way to make this a setting that each user can toggle.

**Comment by Hukuma1** [comment]
Surprised BS doesn't have any scrollbar skinning abilities...

Love your new logs feature and thought maybe we could add custom scrollbars for Machinaris to match the current dark theme?

http://webkit-scroll-gen.sourceforge.net/ = quick generator to make the code

https://caniuse.com/?search=webkit-scrollbar shows support to be over 91% of all browsers. Sorry Firefox... :/

**Comment by Hukuma1** [comment]
<img width="807" alt="machscroll" src="https://user-images.githubusercontent.com/54511555/119728925-de270300-be28-11eb-897d-a7eab085ac16.png">

```
<style type="text/css">
::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}
::-webkit-scrollbar-button {
  width: 0px;
  height: 0px;
}
::-webkit-scrollbar-thumb {
  background: #3aac59;
  border: 0px none #ffffff;
  border-radius: 3px;
}
::-webkit-scrollbar-thumb:hover {
  background: #3aac59;
}
::-webkit-scrollbar-thumb:active {
  background: #3aac59;
}
::-webkit-scrollbar-track {
  background: #15171a;
  border: 0px none #ffffff;
  border-radius: 3px;
}
::-webkit-scrollbar-track:hover {
  background: #15171a;
}
::-webkit-scrollbar-track:active {
  background: #15171a;
}
::-webkit-scrollbar-corner {
  background: transparent;
}
</style>
```

**Comment by guydavis** [comment]
@Hukuma1 Sorry, just spotted this!  Great suggestion on the scrollbars.  You are a wizard at the UI my friend.  I'll include in next release!  Hopefully next week.
