### ISSUE TITLE
Add Bladebit Memory Only Plotter

### ISSUE THREAD

**Issue by rangulicon** [guydavis/machinaris#244]
It would be fantastic to spice things up and get another hyper-performance-focused plotter added to Machinaris.

Bladebit was designed from the ground up to be optimized for memory-only plotting.

The GitHub for Bladebit can be found here: https://github.com/harold-b/bladebit

**Comment by colbyboles** [comment]
I second this. It may happen without any effort here as I have seen some pull requests for plotman to add bladebit support.

**Comment by guydavis** [comment]
Agreed! Would be a nice enhancement.  I'm keeping my eye on [the great work](https://github.com/ericaltendorf/plotman/pull/916) being done in Plotman.

**Comment by guydavis** [comment]
Closing as available in v0.5.5.
