### ISSUE TITLE
no keys found in different directory

### ISSUE THREAD

**Issue by profiesy** [guydavis/machinaris#25]
I am having issues changing the directory of the keys location. 

When I make the path /mnt/user/Video files/mnemonic.txt It will not detect the text file I have in there, It also will not create a new key. 

I get this error when trying to create a new one. 

"Unable to save mnemonic to /mnt/user/Video files/1/mnemonic.txt"

What am I doing wrong?

**Comment by Timi7007** [comment]
You seem to have the wrong path for "mnemonic". The path for this needs to be within the container e.g. ```/root/.chia/mnemonic.txt``` This ```/root/.chia```-directory is then mapped to the host system using the "appdata"-variable.

So setting "appdata" to ```/mnt/user/appdata/machinaris``` and "mnemonic" to ```/root/.chia/mnemonic.txt``` will put your mnemonic.txt in ```/mnt/user/appdata/machinaris/mnemonic.txt```

**Comment by guydavis** [comment]
Closing as resolved with path fix.  Thanks!
