### ISSUE TITLE
Option to remove stale/sleeper Nodes

### ISSUE THREAD

**Issue by ApfelBirneKreis** [guydavis/machinaris#258]
Option to close or remove a connection to a stale Node on the Network Page.

Unfortunatelly i get connected to sleeper nodes very often. This results in a very long syncroisation time. Would be very helpful if we get the option to remove nodes on the Page instead of typing the commnad in the console all the time.

**Comment by guydavis** [comment]
Good suggestion! I'll look for a way to add this cleanly to the WebUI.

**Comment by ApfelBirneKreis** [comment]
Nice! looks very good!

One small problem machinaris does not allow to manually connect to ipv6 adresses

![image](https://user-images.githubusercontent.com/84158946/133881792-11abe0d9-a928-4388-a412-50eae0d67b07.png)

[Host]:[Port] does not wok either. 

Is there a special syntax that i need to use?

**Comment by guydavis** [comment]
Hi, not so much Machinaris as even trying to give the Chia binary seems to fail: 

![image](https://user-images.githubusercontent.com/12936/133907727-45b3926a-4334-40e2-bcb6-4f52f00ab222.png)
