### ISSUE TITLE
Plot Count Does Not Update

### ISSUE THREAD

**Issue by cjackson234** [guydavis/machinaris#264]
**Describe the bug**
Total Plots does not update on the index page. The Farming tab (/farming/plots) shows the correct count.

**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Wait for app to finish loading
2. Add plots to a watched folder
3. Farming tab updates
4. Index does not

**Expected behavior**
I would expect the page would periodically poll to updated

**System setup:**
 - OS: Unraid
 - Docker version number 20.10.5
 - Machinaris branch: main
 - Machinaris version number 0.5.4

**Comment by guydavis** [comment]
Hi, sorry to hear you're encountering this.  Please attach your log file: /mnt/user/appdata/machinaris/machinaris/logs/apisrv.log

Also, please enter the Docker tab console for Machinaris (via the Unraid UI) and type: 
`chia farm summary`.  Please attach output here.  

Thanks.

**Comment by guydavis** [comment]
Thanks for the log.  It contains no errors on updating status, however there are a number of duplicated plot listings, perhaps due to mounting.  Would you mind sharing from your Machinaris fullnode/controller:
```
chia plots show
env | grep plots_dir
ls /
```

I see you have a remote harvester.  Please also share the top-level Workers page, along with the specific Worker page for each of your two workers (fullnode & harvester).  In particular, I'm interested to see if you have a Warning displayed for either/both of them.

**Comment by cjackson234** [comment]
env | grep plots_dir
ls /Directories where plots are being searched for:
Note that subdirectories must be added manually
Add with 'chia plots add -d [dir]' and remove with 'chia plots remove -d [dir]' Scan and check plots with 'chia plots check'

/plots
/plots2
/plots3
/plots4
/plots5
/plots6
/plots7
/plots8
/plots9
# plots_dir=/plots:/plots2:/plots3:/plots4:/plots5:/plots6:/plots7:/plots8:/plots9
# 
:                dev              id_rsa  machinaris  plots2  plots7  run   usr
bin              etc              lib     media       plots3  plots8  sbin  var
boot             flax-blockchain  lib32   mnt         plots4  plots9  srv
chia-blockchain  flaxdog          lib64   opt         plots5  proc    sys
chiadog          home             libx32  plots       plots6  root    tmp

**Comment by cjackson234** [comment]
![image](https://user-images.githubusercontent.com/2728668/131781473-af34fa2f-e08c-42f8-9296-3c0d12dba376.png)

**Comment by cjackson234** [comment]
![image](https://user-images.githubusercontent.com/2728668/131781524-6fd2b9a5-a3a0-4aaa-a157-32a6578f4d62.png)

**Comment by cjackson234** [comment]
![image](https://user-images.githubusercontent.com/2728668/131781606-cfd677f1-119e-4762-954b-984a83c94f60.png)

**Comment by cjackson234** [comment]
It's important to note the the new plots are being adding to the full node NOT the harvester only node.

**Comment by guydavis** [comment]
Interesting, so I recommend is correcting the duplicate plots being held on both your `/plots5` and `/plots9` location, plus also seems like '/plots' and '/plots2'.  Correcting the duplication should help reveal further issues.

Here are some selected examples from the apisrv.log you provided:
```
[2021-09-01 16:16:49 -0400] [1347] [INFO] Skipping addition of plot at /plots9/plot-k32-2021-08-29-22-10-8a969f93f348c95048c9085467cbf96463b28b1b1abc624505658c72b215c065.plot because same plot_id found at /plots5/plot-k32-2021-08-29-22-10-8a969f93f348c95048c9085467cbf96463b28b1b1abc624505658c72b215c065.plot
[2021-09-01 16:16:49 -0400] [1347] [INFO] Skipping addition of plot at /plots2/plot-k32-2021-07-18-05-06-67eb287ae9b66f33e31f2bbf3c8706eecc5cd38522e96c641d28140cf1916d6f.plot because same plot_id found at /plots/plot-k32-2021-07-18-05-06-67eb287ae9b66f33e31f2bbf3c8706eecc5cd38522e96c641d28140cf1916d6f.plot
```

**Comment by guydavis** [comment]
Any luck with this?  I also recommend trying the latest "[:test](https://github.com/guydavis/machinaris/wiki/Releases#release-streams)" image by adding that suffix to the Docker run/compose you are launching with.

**Comment by cjackson234** [comment]
None. I'll try the test branch shortly.

**Comment by cjackson234** [comment]
Farming tab - Showing 1 to 25 of 172 entries

Summary tab - 1513 plots

**Comment by guydavis** [comment]
Right, you have 3 Machinaris installs as per screenshot above. Did you upgrade all 3 or just the Machinaris fullnode/controller named 'Elias'?

**Comment by guydavis** [comment]
> Interesting, so I recommend is correcting the duplicate plots being held on both your `/plots5` and `/plots9` location, plus also seems like '/plots' and '/plots2'. Correcting the duplication should help reveal further issues.
> 
> Here are some selected examples from the apisrv.log you provided:
> 
> ```
> [2021-09-01 16:16:49 -0400] [1347] [INFO] Skipping addition of plot at /plots9/plot-k32-2021-08-29-22-10-8a969f93f348c95048c9085467cbf96463b28b1b1abc624505658c72b215c065.plot because same plot_id found at /plots5/plot-k32-2021-08-29-22-10-8a969f93f348c95048c9085467cbf96463b28b1b1abc624505658c72b215c065.plot
> [2021-09-01 16:16:49 -0400] [1347] [INFO] Skipping addition of plot at /plots2/plot-k32-2021-07-18-05-06-67eb287ae9b66f33e31f2bbf3c8706eecc5cd38522e96c641d28140cf1916d6f.plot because same plot_id found at /plots/plot-k32-2021-07-18-05-06-67eb287ae9b66f33e31f2bbf3c8706eecc5cd38522e96c641d28140cf1916d6f.plot
> ```

Also, did you sort out the duplicate plots that seem to be in multiple folders as per this comment from a few days back?

**Comment by cjackson234** [comment]
Just the full node Elias gets updated. The plotter wouldn't effect counts and the harvester GlaDOS is all that is listed in the counts on the farmer screen. That means that Elias on the new code branch is likely the issue.

**Comment by cjackson234** [comment]
Not sure dupes are what is causing this, but I can test that quickly as well.

**Comment by guydavis** [comment]
Please attach: machinaris/logs/apisrv.log

**Comment by cjackson234** [comment]
[apisrv.log](https://github.com/guydavis/machinaris/files/7149346/apisrv.log)

**Comment by guydavis** [comment]
Hi, thanks for the logs.  I see database lock issues, so let's reset it:

1. Stop Machinaris container
2. Delete this file: ~/.machinaris/machinaris/dbs/machinaris.db
3. Unraid Admin UI - Docker tab - edit Machinaris container, add `:test` to end of the Repository line.
4. Start Machinaris conainer

Give it about 10-15 minutes to get started fully and populate some status.  Please let me know if that helps.

**Comment by cjackson234** [comment]
Updating counts still does not work. Also, the farming page is incorrect again.

**Comment by guydavis** [comment]
Alright, please upgrade to the latest release v0.5.5 of Machinaris (on all your installs, controller and workers).  Then please allow 30 minutes for status to update.  Please share screenshots of the following using the latest version:

- Workers page
- Summary page
- Farming page - showing bottom of table indicating total counts.

**Comment by cjackson234** [comment]
![image](https://user-images.githubusercontent.com/2728668/133800357-5f0794cf-fe84-4c10-91b8-781e739776f5.png)
![image](https://user-images.githubusercontent.com/2728668/133800441-c442c692-d0fc-43e8-a212-e0d11b707f5d.png)
![image](https://user-images.githubusercontent.com/2728668/133800506-cb2bf6ef-b5b6-4cec-b9ac-fb260bcd7754.png)

**Comment by cjackson234** [comment]
That's better, but its still updating. I have to restart a few times a day to  get counts to update

**Comment by guydavis** [comment]
Great. Good to see counts agreeing. Latest is version 0.5.6.  Please update all your Machinaris installs when you get a chance.
