### ISSUE TITLE
Wallet "No online backup file found"

### ISSUE THREAD

**Issue by soldius** [guydavis/machinaris#27]
Hello, first of, thank you for putting this together. It really is helpful for me to keep everything in one place. Everything else seems to be good except the wallet feature. I keep getting the "No online backup file found". I forwarded the port and it seems to be syncing (which is taking a while, does it usually take that long?). Could you let me know what what I did wrong? I imported a mnemonic that I was using on the GUI on another PC (turned off now). Thank you.
![Window_ShareX_chrome_2021_05_20_ 07 12 52](https://user-images.githubusercontent.com/44028743/118994451-334faa00-b93b-11eb-8286-afd191317052.png)

**Comment by Timi7007** [comment]
The chia software prompts you to press a key as it wants to know how to handle importing the existing wallet. But you can't press a key as the docker-container doesn't allow for an input of such kind and has since moved on.
I also had this issue, copying in an old .chia/mainnet folder fixed it.

**Comment by soldius** [comment]
> The chia software prompts you to press a key as it wants to know how to handle importing the existing wallet. But you can't press a key as the docker-container doesn't allow for an input of such kind and has since moved on.
> I also had this issue, copying in an old .chia/mainnet folder fixed it.

This works perfectly. Although I only copied the wallet folder within mainnet folder. Thank you for sharing this trick :)

**Comment by guydavis** [comment]
Thanks for catching this one in v0.1 on a fresh install.  I've improved the fresh install experience in v0.2 so this no longer happens to those that ask Machinaris to [generate a key](https://github.com/guydavis/machinaris/wiki/Keys).  Apologies for the rough edges of the setup process in v0.1.  Thanks for testing though!
