### ISSUE TITLE
Feature Request - Add Proofs to blockchain scatter chart

### ISSUE THREAD

**Issue by marshalleq** [guydavis/machinaris#272]
Hi, until now (only installed Machinaris yesterday night), I've been using a nice little project called Chiaharvestgraph [here](https://github.com/stolk/chiaharvestgraph).  Your blockchain scatter chart could implement the same principle really, different colours for different events.

![image](https://github.com/stolk/chiaharvestgraph/blob/main/images/screenshot0.png?raw=true)

One of the things I liked was how easy it was to link up e.g. an ISP outage with the chart - the NZ fibre providers seem to have a lot of maintenance around midnight, I assume on my Fibre Terminal.  It's also great having the proofs and challenges on one chart, which makes things super nice.  But that aside, it is probably the most interesting and useful chart I've seen so far.  Perhaps you could do something similar or contact Stolk to see if you can collaborate on something.

Nice job with this container by the way.  I was starting to get a bit nervous about how I could check my chia health - for example the challenge with the above tool is I needed to keep a 24 bit console open in linux and you seem to have solved it for me!

Early days I guess, but it looks great so far!

Thanks again,

Marshalleq

**Comment by guydavis** [comment]
Very cool chart.  I see that it works for a single host, single blockchain, so the separate colors make sense there.  I wonder how I might do something similar on the Summary page of Machinaris where each color corresponds to a Harvester/Blockchain pairing.  Maybe we need individual charts on the Farming | Worker page to show this?

**Comment by marshalleq** [comment]
I think both the Blockchain Challenges to Harvesters graph AND the partial proofs to pools chart could be expanded to include the data from the other graph.  Then yes, adding the one I suggest above probably does make more sense on the farming page.  Hopefully aligning colours to the summary page charts to remove any confusion.

E.g. 
1. The Blockchain challenges scatter graph could have another colour that shows the proofs as well (giving a nice representation of frequency of proofs)
2. The Partial Proofs chart could also have challenges added as a second colour.
3. Adding the chia harvest graph to the farming page

In this way, we'd get two different views of the same data on the summary page giving a good overview going back an hour, one that views well for understanding recent timing and function of the system, the other for understanding a count of what's been going on.  

And we'd get details of the farming going back as far as the logs on the farming page.

Does that make sense?

I really miss this chart, but it requires a 24bit colour console, so I have to run up a linux box to use it (Mac doesn't have 24 bit console).  

Thanks.

**Comment by guydavis** [comment]
Hi again!  Sorry, I did see your response.  Just haven't had a chance to get to this.  Need to get v0.6.0 out the door and then I'll be evaluating possible new features such as this.  Will re-visit it then.  Thanks again for the suggestion.

**Comment by guydavis** [comment]
Upcoming release will chart (and list) farmed blocks along with wallet balances and more.  Thanks for the suggestion.

**Comment by marshalleq** [comment]
Oooh, very nice thank you!

**Comment by guydavis** [comment]
Machinaris [version 0.8.0](https://github.com/guydavis/machinaris/releases/tag/0.8.0) has now been released with support for Chia 1.4.0.  Thanks!
