### ISSUE TITLE
Feature request: Estimated time to win + statistics

### ISSUE THREAD

**Issue by abra1c** [guydavis/machinaris#28]
Why is there nowhere the estimated time to win in the UI?
And it would be great to have statistics and graphs about the plotting process.

**Comment by guydavis** [comment]
Honestly, because I've been coding too much and neglecting my plotting duties so my `Estimated Time to Win` is too sad.  :(

These are great suggestions though, I'll try to add them soon as I can.  Thanks for the feedback.

**Comment by guydavis** [comment]
Hi, as an update, the `Expected Time to Win` is now shown on the Farming page in test version `ghcr.io/guydavis/machinaris:test`.  Will be released to mainline in coming week.  Additional statistics of various types coming in the future.  Great suggestions!
