### ISSUE TITLE
configurable status collection interval

### ISSUE THREAD

**Issue by abien** [guydavis/machinaris#288]
As [discussed on discord](https://discord.com/channels/842422792593866782/842488536036147210/887715722959151146) :
i propose to create config option to set the status collection interval. This should allow commands like 
```
chia keys show 
chia show --connections
(...) farm summary 
```
.. and the likes to run less frequent. Currently it seems to run every minute.
This should be implemented for every supported blockhain (currently chia & flax)

Reason beeing: Smaller platforms like a Raspberry Pi might want to use precious cpu cycles for other activities.

**Comment by guydavis** [comment]
Hi, good suggestion.  I'll make this a configurable setting, but I would like a good default value for Machinaris fullnode on a RaspPi.  Would you mind doing the following on your RaspPi?
```
uname -m
```
I'm interested to see if you get `aarch64` back as your architecture.  I can use this value to set a reasonable default (say every 3-5 minutes, instead of every minute) on a fresh install.

**Comment by abien** [comment]
It is aarch64 :)

```
~$ uname -m
aarch64
```

**Comment by abien** [comment]
**Raspberry Pi CPU Usage (pre #288)**
```
00:00:40        CPU     %user     %nice   %system   %iowait    %steal     %idle
08:00:02        all     19.33      0.00      8.66      4.65      0.00     67.36
08:10:02        all     15.27      0.00      4.45      1.49      0.00     78.78
08:20:02        all     45.89      0.00      7.79      2.08      0.00     44.25
08:30:02        all     44.59      0.00      8.26      2.26      0.00     44.89
08:40:02        all     44.18      0.00      8.85      2.00      0.00     44.97
08:50:02        all     38.03      0.00      6.36      2.46      0.00     53.15
09:00:02        all     41.78      0.00      8.11      1.84      0.00     48.26
```

**Raspberry Pi CPU Usage (with latest :test including changes from #288)**
```
00:00:40        CPU     %user     %nice   %system   %iowait    %steal     %idle
08:10:16        all     20.69      0.00      4.80      2.41      0.00     72.10
08:20:29        all     15.04      0.00      2.38      2.08      0.00     80.50
08:30:29        all     15.87      0.00      2.69      2.37      0.00     79.07
08:40:06        all     19.59      0.00      4.49      2.46      0.00     73.45
08:50:21        all     16.41      0.00      2.55      3.13      0.00     77.91
09:00:29        all     18.23      0.00      3.61      3.77      0.00     74.39
```
The change saves about 25% cpu capacity. Good job.
Is this configurable though?

**Comment by guydavis** [comment]
Good to hear!  Yes, the value is configurable and found in ~/.machinaris/config/api.cfg.  

Key is: STATUS_EVERY_X_MINUTES

On a standard Machinaris install on x86_64, the implicit default is once per minute (so STATUS_EVERY_X_MINUTES = 1).

In v0.5.6 (just about released), this file is created on aarch_64 (when Machinaris fullnode/controller) with STATUS_EVERY_X_MINUTES = 4.  This means status is sent 4x less frequently.  

That you recorded only a 25% CPU savings tells you just how much CPU this Machinaris status gathering was costing, as compared to baseline CPU just to run Chia farming and wallet services, which are unchanged by this variable.

So, if you want to dial back Machinaris status updates even more, edit that file, set the value to 10 (every 10 minutes) for example, and then restart the Machinaris container.  Just bear in mind that Machinaris WebUI status display will be at least 10 minutes behind at that point.

Thanks so much for testing Machinaris as a fullnode/controller on RaspPi!

Also, as an aside, this does NOT affect a Machinaris harvester/worker install on RaspPi, which connects to another system (Windows/Linux/etc) running the Machinaris fullnode/controller elsewhere on the LAN.  This harvester-only RaspPi deploy has always run pretty well as Chia/Flax/Machinaris are all running much fewer services in that case.

**Comment by guydavis** [comment]
Closing as now available in [released v0.5.6](https://github.com/guydavis/machinaris/releases/tag/0.5.6) version.  Great suggestion!

**Comment by Enissay** [comment]
Is this only active for RPi ? why not on all? 
My minis farming machine is struggling as well and could benefit from a 25% CPU saving, why not make this flag optional for all ?

**Comment by guydavis** [comment]
Good day!  I'm always happy to answer your urgent questions directed at me.  This flag is already found in ~/.machinaris/machinaris/config/api.cfg.  Just change `STATUS_EVERY_X_MINUTES` from default of 2 and restart the container. You are welcome to decrease the frequency.

That said, to set your expectations, farming using a fullnode is a resource-intensive process as the recent Chia dust storm showed.  The fullnode must do all the work of participating in the blockchain.  

The status gathering frequency above, only affects the monitoring being performed by Machinaris, which is small overhead compared to the actual fullnode/farming effort itself.  Please check your expectations.

Much more important is to run only the Chia fullnode on such a small system, do not add any [fullnodes for forks](https://github.com/guydavis/machinaris/wiki/Forks).  Best of luck to you!

**Comment by Enissay** [comment]
Well noted, thank you
