### ISSUE TITLE
Show more precise info in the plotting analysis (seconds)

### ISSUE THREAD

**Issue by efnats** [guydavis/machinaris#289]
In the plotting analysis currently the total amount taken for a plot is being shown in 1000 seconds. For example 1.4k instead 1482.

For those of us who are trying to improve on their plotting speeds this number is quite important and it would help to not get rounded but exact information of the time it took to create the plot.

**Comment by guydavis** [comment]
Unfortunately, this rounded value is coming out of Plotman, not Machinaris.  Makes sense as Plotman was written when only the slow Chia plotter was avaiable, so rounding to the 1000s was no issue.  Now, months later we have Bladebit and Madmax which are so much faster. I'll have to take a look at patching that project's upstream.

**Comment by efnats** [comment]
I have checked this again and using (a modified) method jm suggested here [https://chiadecentral.com/nuc-small-form-factor-plotting-build/](url) it is possible to get good average statistics for a specific plotter by using this command:

`grep -i "creation time" ~/machinaris/plotman/logs/*.plot.log | awk '{sum=sum+$6} {avg=sum/NR} {tday=86400/avg*6*101.366/1024} END {printf "%d K32 plots, avg %0.1f seconds, %0.2f TiB/day \n", NR, avg, tday}'
`
`335 K32 plots, avg 1800.2 seconds, 28.51 TiB/day`

 Maybe this could be used somewhere in the overview or the workers tab in "farming".

**Comment by guydavis** [comment]
Hi, good suggestion.  I am working on this and other improvments.  Now no longer rounding to thousands in latest dev stream: 

![image](https://user-images.githubusercontent.com/12936/140661453-b3747a41-9755-4b76-ad27-743bdd92d161.png)

**Comment by guydavis** [comment]
This has been released with v0.6.4.  Thanks again for the suggestion.
