### ISSUE TITLE
Farmr.net integration

### ISSUE THREAD

**Issue by depasseg** [guydavis/machinaris#299]
**Describe the request**
Add farmr.ner integration which would provide the ability to monitor single or multiple farms.

**Images**
![image](https://user-images.githubusercontent.com/3201827/134183862-7783aece-47c1-446d-b1e8-58dc8a2f5756.png)

**Additional comments**
https://github.com/joaquimguimaraes/farmr

**Comment by ApfelBirneKreis** [comment]
Would be awesome!

**Comment by guydavis** [comment]
Great suggestion.  This support for [Farmr](https://github.com/guydavis/machinaris/wiki/Monitoring#farmr) will be part of the upcoming v0.6.4 release.

**Comment by guydavis** [comment]
This has been released with v0.6.4.  Thanks again for the suggestion.
