### ISSUE TITLE
Feature for distributed plotting/farming

### ISSUE THREAD

**Issue by kdg1992** [guydavis/machinaris#3]
A feature that can plotting on a dedicated or multiple device and auto transfer to the farmer would be very nice.

**Comment by guydavis** [comment]
Yes, very cool idea.  The official Docker image handles this by [setting environment variables](https://github.com/Chia-Network/chia-docker/blob/main/Dockerfile#L7) to enter harvester-only mode.  I'll see if I can do something for plotting only.  Then the Machinaris WebUI will only show the relevant functions running on that node.  Great suggestion!

**Comment by guydavis** [comment]
So, in the last two weeks, with the improvements to the [different modes](https://github.com/guydavis/machinaris/wiki/Generic#full-node) supported by Machinaris, its become clear that some distributed communications support amongst Machinaris nodes would be useful.  

Ideally, the Machinaris fullnode would present a single monitoring pane showing all the Machinaris nodes in the overall farm.  Each "worker" node would connect back to the fullnode to report status and receive control.  

Feel free to add ideas here on how best we can accomplish this distributed architecture.  Thanks all!

**Comment by cm86** [comment]
So the quick and dirty way would be to have just iframes in the mainnode to control the webui from the subnode trough the mainnode...
because of all provide a webui...

the desirable way would be to have a database running on the mainode and let every subnode report into the database...
the subnode also have to watch into the database, to control them through the mainode...

... puh ... first shot ... let's discuss

**Comment by GTANAdam** [comment]
> So, in the last two weeks, with the improvements to the [different modes](https://github.com/guydavis/machinaris/wiki/Generic#full-node) supported by Machinaris, its become clear that some distributed communications support amongst Machinaris nodes would be useful.
> 
> Ideally, the Machinaris fullnode would present a single monitoring pane showing all the Machinaris nodes in the overall farm. Each "worker" node would connect back to the fullnode to report status and receive control.
> 
> Feel free to add ideas here on how best we can accomplish this distributed architecture. Thanks all!

RESTful API or Websocket.
Auto-discovery and manual node addition.

**Comment by guydavis** [comment]
Hi all! Using a single Machinaris controller instance (WebUI) to manage [multiple Machinaris workers](https://github.com/guydavis/machinaris/wiki/Workers) on your LAN is now available in the test version.  Please give it a try and provide your feedback here!

**Comment by guydavis** [comment]
Closing as v0.4.0 has been released.  Thanks for the contribution!
