### ISSUE TITLE
Whenever Machinaris restarts, the Chia fullnode doesn't properly start.

### ISSUE THREAD

**Issue by TheOddball** [guydavis/machinaris#301]
**Describe the bug**
Whenever Machinaris restarts, the Chia fullnode doesn't properly start.

**To Reproduce**
Restart Machinaris
View Chia Logs

**Expected behavior**
Chia works immediately

**System setup:**
 - OS: TrueNAS Scale
 - Docker version number (output of `docker info`): v0.9.1-beta3
 - Machinaris branch: Main
 - Machinaris version number: 0.5.6

**Additional context & screenshots**
Constant logging of
`2021-09-27T18:13:38.519 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7f682db68f40> [Connect call failed ('127.0.0.1', 8444)]`

Fullnode seems to halt at
`2021-09-27T18:14:50.522 full_node chia.full_node.full_node: INFO     Initializing blockchain from disk
2021-09-27T18:14:50.524 full_node chia.consensus.blockchain: INFO     Started 22 processes for block validation`

This could be an issue with my specific machine, I don't quite know.

**Comment by guydavis** [comment]
Good day, sorry to hear you're encountering this issue with Chia binaries in the Machinaris image.  Could be a corrupted blockchain database.  My recommendation:

1. Stop Machinaris container
2. Delete the 'mainnet' folder from the container's AppData folder.  Sometimes ~/.machinaris, not sure where on TrueNas.
3. Start Machinaris container.  Wait for status to re-populate, may take a day or more to re-sync.

Hope this helps.

**Comment by TheOddball** [comment]
I'll give it a try, thanks! Will update back with the results

**Comment by ApfelBirneKreis** [comment]
I had the same Problem. I managed to resolve it by moving the chia blockchain db to an nvme. It has soething to do with an overloaded or slow disk speed. By every restart Chia/machinaris has to load the blockchain and wallet db this can take avery long time since it's now pretty huge.

Try moving it to an nvme or SSD and avoid storing it on an HDD.
