### ISSUE TITLE
Add ansible support

### ISSUE THREAD

**Issue by HitLuca** [guydavis/machinaris#316]
I am currently running Machinaris on my two machines, and I now would like to convert my main farmer/controller to also be a NAS. I found this awesome project called [ansible-nas](https://github.com/davestephens/ansible-nas), which uses ansible to automagically install on a remote machine many different types of utilities which are convenient to have (plex streaming, movie download, backup utilities, home automation etc.).

I was wondering if there could be interest into making this project a simple plug-and-play ansible role, since both tools compliment each other and ease deployment on new machines

@guydavis let me know what you think, I can look into this feature myself, even though I started learning ansible one week ago.

To make this happen we should only need an ansible role, like the ones available for the mentioned project [here](https://github.com/davestephens/ansible-nas/tree/master/roles). You would creare the needed folders, get the required folder and port mappings (from a config) and then spin up machinaris from that

**Comment by guydavis** [comment]
Closing as stale.
