### ISSUE TITLE
[feature request] - Control the plotter during the WEBUI of fullnode

### ISSUE THREAD

**Issue by cm86** [guydavis/machinaris#33]
This would be i nice feature to controll the plotter during the webui of the fullnode.
May be to sum up all plotters in the "Plotting" Section...

Maybe we could get this working through a database somewhere else (in unraid just a small mariadb/mysql/postgres docker --> would prefer postgres because i have already one running).
In the DB the could all poll there states and i would start a transaction i the state in the DB changes...
--> just a suggestion

**Comment by guydavis** [comment]
Good suggestion.  A distributed setup of multiple machines all reporting back to a central instance of Machinaris for summary display would be awesome.  Just tricky... I'll think on it.  Thanks again!

**Comment by guydavis** [comment]
Hi! Using a single Machinaris controller instance (WebUI) to manage [multiple Machinaris workers](https://github.com/guydavis/machinaris/wiki/Workers) on your LAN is now available in the test version.  Please give it a try and provide your feedback here!

**Comment by guydavis** [comment]
Closing as v0.4.0 has been released.  Thanks for the contribution!
