### ISSUE TITLE
Automatic plot check for new plots - display good/bad status of plots on Farming page.

### ISSUE THREAD

**Issue by guydavis** [guydavis/machinaris#339]
With increasing farm size, a background process to periodically run a `chia plots check` on all plots (particularly new ones) would be useful.  Farming page would display the status of each plot, sortable so one could find any plots flagged as problematic.

**Comment by toto99303** [comment]
Awesome!! Can't wait for this :)

**Comment by ricknorton** [comment]
I like that this is built into the UI but can it include the option to toggle on/off or disable, or include the ability to specify how often it runs? I'd really only want to run this on new plots or choose to manually run it at a later time as it is currently impactful to how I have things set up across multiple forks, fileshares, and servers.

**Comment by guydavis** [comment]
Yes, v0.6.7 will allow you to set `plots_check_analyze_skip` environment variable if you wish to disable automatic checks.
