### ISSUE TITLE
[feature request] - statistic for already done plots

### ISSUE THREAD

**Issue by cm86** [guydavis/machinaris#34]
when you grep the logfile files you can get the totaltime by last plotting processes...
`cat /mnt/user/appdata/machinaris/config/plotman/logs/* | grep "Total time"`
--> the output looks like this
`Total time = 46063.301 seconds. CPU (95.470%) Thu May 20 08:36:40 2021
Total time = 45165.172 seconds. CPU (102.620%) Thu May 20 21:20:07 2021`

Here you can create a nice table and maybe altough calculate the total time up to hh:mm:ss

**Comment by guydavis** [comment]
Yes, great suggestion.  I want to leverage the Plotman analyze feature for this.  Hope to get it working soon!

**Comment by guydavis** [comment]
Plotman Analyze has been added as a button to the right of each plot in Farming view.  If the Plotman log for the plot is found, the Analyze is shown:

![image](https://user-images.githubusercontent.com/12936/119924775-714b6000-bf31-11eb-99d0-90f879e94c03.png)

However, if the plot was made elsewhere (and Plotman log not also copied over), then a message is shown instead:
![image](https://user-images.githubusercontent.com/12936/119924842-8de79800-bf31-11eb-9d70-364fdfc680c4.png)

Will be available in the v0.3.0 release.  Thanks!
