### ISSUE TITLE
Archiving option gone

### ISSUE THREAD

**Issue by bingemer** [guydavis/machinaris#344]
**Describe the bug**
In previous version I was able to start/stop archiving on the "Plotting" page, now the options are gone and I was not able to find it anywhere else.

**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Run Machinaris
2. Configure plotting
3. Configure archiving
4. Start plotting
5. Archiving options (Start/Stop and Log) missing

**Expected behavior**
https://github.com/guydavis/machinaris/wiki/Plotman#archiving
4. Finally, to start Plotman Archiving within Machinaris, visit the Plotting page, select the drop-down for your Worker, and choose 'Start Archiving'.

**System setup:**
 - OS: Debian 10/11
 - Docker version number: 20.10.9
 - Machinaris branch: main
 - Machinaris version number: 0.7.0

**Config**
<details><summary>full configuration</summary>

```
docker run \
    --restart unless-stopped \
    -d -t --name machinaris \
    -h dl560g8.rieste \
    --dns 10.0.255.1 \
    -v ~/.machinaris:/root/.chia \
    -v ~/.ssh:/root/.ssh:ro \
    -v /mnt:/mnt \
    -v /srv:/srv \
    -e TZ=Europe/Berlin \
    -e farmer_address=192.168.0.101 \
    -e farmer_port=8447 \
    -e flax_farmer_port=6885 \
    -e farmer_pk=FARMERKEY \
    -e pool_pk=POOLKEY \
    -e pool_contract_address=CONTRACTADDRESS \
    -e mode=harvester,plotter \
    -e controller_host=192.168.0.101 \
    -e controller_api_port=8927 \
    -e worker_address=10.0.255.79 \
    -e plots_dir=/srv:/mnt/tr9:/mnt/tr10 \
    -e blockchains=chia \
    -e AUTO_PLOT=false \
    -p 8927:8927 \
    ghcr.io/guydavis/machinaris
```

</details>

**Additional context & screenshots**
<!-- Add any other context about the problem here, including full page screenshots. --
![Snag_242a2498](https://user-images.githubusercontent.com/17237845/138042076-ff20726e-10c6-43ec-aeb7-5448b17ceb66.png)
>

**Comment by istarion** [comment]
Temporary workaround (you can also configure ```autostart_archiving: True```):
```
curl -X POST -H "Content-Type: application/json" -d '{"service": "archiving","action": "start"}' http://localhost:8927/actions/
```

**Comment by guydavis** [comment]
Hi! Thanks for the report.  Great to know that Plotman archiving is being used in Machinaris.  Apologies for the loss of the button controls in v0.6.0.  I have just added them back in the upcoming v0.6.1 version:

![20211020_195826](https://user-images.githubusercontent.com/12936/138198554-ef603263-9480-4a70-8129-391722b9e70c.png)

Workaround in the meantime (similar to the suggestion from @istarion) is to remote to the worker system in question and:
```
docker exec -it machinaris bash
plotman archive
```
This will start archiving in the foreground.  Apologies again.
