### ISSUE TITLE
Better Use of Container Layering

### ISSUE THREAD

**Issue by DarkRider1768** [guydavis/machinaris#347]
Just deployed this via Docker with a generated compose file from the main site; when deploying all 4 of the current coins, the diskspace usage on the boot drive balloons to nearly 8GB in container images. I suspect the images have quite a lot of overlap and that it'd be beneficial to build a Dockerfile as a base image and then use that base image to build from for the other coins.

**Comment by Bafff** [comment]
@guydavis hi!

Do you need any help with this?

**Comment by guydavis** [comment]
Sure! All [contributions ](https://github.com/guydavis/machinaris/wiki/Contributing)are welcome.  In this case, a well-tested PR with available Docker images that can be validated would be great.  Given such a changes impact on the images themselves, full regression testing is required to avoid breakage.

**Comment by guydavis** [comment]
Alright, I found time to improve this.  Still testing, but so far it looks like I have the image size down to about 40% the size of earlier versions.  As well, the common base image, which is 2/3 of the remainder, should now be shared amongst all fork containers.

![image](https://user-images.githubusercontent.com/12936/141685922-0e878c3b-958f-4a3c-ad6b-6126385fcc8a.png)

**Comment by Bafff** [comment]
@guydavis hi!

Can you give some insights of how you optimized your build? I looked into but could not find easy ways to improve it :(

**Comment by guydavis** [comment]
Common base image + other slimming techniques.  The optimized images are now available in the [`:test` stream](https://github.com/guydavis/machinaris/wiki/Releases#release-streams).  Please give them a try.

**Comment by guydavis** [comment]
Good day!  [Version 0.6.5](https://github.com/guydavis/machinaris/releases/tag/0.6.5) has now been released.
