### ISSUE TITLE
No Plots show if nfs share remounted in container 

### ISSUE THREAD

**Issue by spqr2001** [guydavis/machinaris#35]
Hi , 
first: great work ! I have only one issue , its seems that the gui wont show plots if they are mounted as nfs share on the host and then remounted inside the containert.  On the cli chia farm summary shows all plots and dirs , chia plots check also recognize the plots inside the dirs,. The gui shows in home correct values , in farming 0. 
I hope my german english didnt hurts you not to much :-) 

Update: Its not NFS , its just hardocded values for the first plot dir.. Ignore this issue  :-)

**Comment by guydavis** [comment]
Glad to hear you got it working.  Hopefully this [guide ](https://github.com/guydavis/machinaris/wiki/FAQ#can-i-use-two-or-more-final-destination-directories-to-hold-my-plots) on configuring multiple plot directories helped.

**Comment by CyberSardinha** [comment]
I actually have the same problem. What is the hardcoded values for the first plot?
I want to check if that is my problem as well

**Comment by hhollenstain** [comment]
@guydavis Would something like yaml parsing the chia config for the farming directories make more sense then having to set this twice? It seems pretty trivial if I have time I can take a look at adding it.

**Comment by hhollenstain** [comment]
@guydavis ignore my previous comment, i see you are looping the env_var and adding it to the chia config.
