### ISSUE TITLE
Forks: Support for Cannabis chain

### ISSUE THREAD

**Issue by cr8tor456** [guydavis/machinaris#361]
It would be great to see this fork added as another optional container.
It uses existing chia plots also

**Comment by guydavis** [comment]
When checking with our [Discord ](https://discord.gg/mX4AtMTt87) in the #feature-ideas channel about which fork to support next, it looks like Dogechia, Greendoge, and Stor are currently the leading contenders.

![image](https://user-images.githubusercontent.com/12936/140570330-679c28eb-e732-4c83-95f5-bdd9c3586bff.png)

Voting is still open, and I'll keep adding supported forks in Machinaris as time allows.

**Comment by guydavis** [comment]
This blockchain didn't get enough votes last time.  [Voting has just opened](https://discord.com/channels/842422792593866782/845378554878754857/951526113396547614) again on the next blockchain to support however.  We'll see how this one does this round.

**Comment by guydavis** [comment]
Closing as this blockchain has had no update for nearly a year now.
