### ISSUE TITLE
Forks: Support for Achi chain

### ISSUE THREAD

**Issue by priyankub** [guydavis/machinaris#362]
It is the only other k32 fork that does not support Chia plots, and was not a direct copy paste. It has grown quite fast in net space as well.
More details: https://achicoin.org/

**Comment by guydavis** [comment]
When checking with our [Discord ](https://discord.gg/mX4AtMTt87) in the #feature-ideas channel about which fork to support next, it looks like Dogechia, Greendoge, and Stor are currently the leading contenders.

![image](https://user-images.githubusercontent.com/12936/140570330-679c28eb-e732-4c83-95f5-bdd9c3586bff.png)

Voting is still open, and I'll keep adding supported forks in Machinaris as time allows.

**Comment by priyankub** [comment]
Thanks for sharing! I noticed Stai is not in that poll. Was it already decided to be added to Machinaris?

**Comment by guydavis** [comment]
This blockchain didn't get enough votes last time.  [Voting has just opened](https://discord.com/channels/842422792593866782/845378554878754857/951526113396547614) again on the next blockchain to support however.  We'll see how this one does this round.

**Comment by guydavis** [comment]
Closing as no updates to this blockchain since last fall.
