### ISSUE TITLE
Forks: Support staicoin

### ISSUE THREAD

**Issue by easleycorey** [guydavis/machinaris#363]
https://www.station-i.de/stai

https://github.com/STATION-I/staicoin-blockchain

List and info of forks I suggest:
https://docs.google.com/spreadsheets/d/1ttIK-TQwwWeY4XarapjKAYJIgDJ5Kk9yjvBPLIlrpdg/edit#gid=0

**Images**

**Additional comments**

**Comment by guydavis** [comment]
Hi, I am testing out Staicoin support now.  However, one Machinaris user is reporting problems getting their harvester to connect to the Staicoin fullnode on port 1692.  Is that the correct port?  Seems to be from the Staicoin config.yaml:

![image](https://user-images.githubusercontent.com/12936/139698524-d0229d55-8da2-4465-8e81-01b3368dc25e.png)

**Comment by guydavis** [comment]
Currently in the `:develop` stream.  My initial testing seems to be going okay.  Will promote this to `:test` stream in next few days.  Thanks for the suggestion!

**Comment by guydavis** [comment]
Available in v0.6.3, now fully released.

**Comment by tjb-altf4** [comment]
@guydavis note the recent release of stai has changed the executable path from staicoin to stai

**Comment by guydavis** [comment]
Thanks for the tip! I believe I've now fixed all the places this renaming broke things in the `:develop` images.  Will hit `:test` next week likely.
