### ISSUE TITLE
Forks: Support Venidium

### ISSUE THREAD

**Issue by easleycorey** [guydavis/machinaris#364]
https://github.com/Venidium-Network/-blockchain

https://venidium.io/home.html

Whitepaper:
https://docs.google.com/document/d/1BumwEw1ICKLFvIOTB_NOvYKn7c4d-ph_-maJzUO7XB4/edit

List and info of forks I suggest:
https://docs.google.com/spreadsheets/d/1ttIK-TQwwWeY4XarapjKAYJIgDJ5Kk9yjvBPLIlrpdg/edit#gid=

**Images**

**Additional comments**

**Comment by guydavis** [comment]
When checking with our [Discord ](https://discord.gg/mX4AtMTt87) in the #feature-ideas channel about which fork to support next, it looks like Dogechia, Greendoge, and Stor are currently the leading contenders.

![image](https://user-images.githubusercontent.com/12936/140570330-679c28eb-e732-4c83-95f5-bdd9c3586bff.png)

Voting is still open, and I'll keep adding supported forks in Machinaris as time allows.

**Comment by guydavis** [comment]
Closing as this blockchain hasn't had an update since last fall.

**Comment by guydavis** [comment]
Alright, got talked into this by Machinaris users on the Discord.  With a blockchain this old, implying high resource usage to run, compared to recently merged chains (against Chia mainline), I won't run this, but maybe the devs will get it updated again.  Re-opening.

**Comment by guydavis** [comment]
![image](https://user-images.githubusercontent.com/12936/186515319-5f194b78-312e-4550-a89c-007c945d9e92.png)
