### ISSUE TITLE
Suspending and updating image kills ongoing plots

### ISSUE THREAD

**Issue by cani1989** [guydavis/machinaris#37]
Is it possible to update without loosing progress on current plots?

**Comment by guydavis** [comment]
No, unfortunately restarting the entire Docker container is a lot like rebooting your PC.  All plotting jobs are killed and can't be resumed.  I recommend that when you have running plots and need to restart/update the image:

1. Plotting | Stop Plotman -> this prevents new plots from being launched, let's existing ones keep running.
2. Wait for existing plots to complete.
3. Then restart/update the Machinaris image/container.

Hope this helps!
