### ISSUE TITLE
nchain config cannot be shown on settings - farming - nchain

### ISSUE THREAD

**Issue by raingggg** [guydavis/machinaris#376]
When you go to see nchain settings, it always display 'internal server error' like message.

I did a debug, and found this can be fixed in file nchain_launch.sh by adding following lines after line# 12(chia init >> /root/.chia/ext9/log/init.log 2>&1):
mkdir -p /root/.nchain
ln -s /root/.chia/ext9 /root/.nchain
mv /root/.nchain/ext9 /root/.nchain/mainnet

Root cause: nchain is using a different ext9 folder for its mainnet. We need to map ext9 as mainnet, instead of simply put mainnet inside of the .nchain.

**Comment by guydavis** [comment]
Thanks for the report!  View/edit of the Settings | Farming page for N-Chain has been fixed in v0.6.2:

![image](https://user-images.githubusercontent.com/12936/139507711-52093232-750c-4319-b151-f7c486bb7d48.png)
