### ISSUE TITLE
Feature Request: Summary and Plotting

### ISSUE THREAD

**Issue by cani1989** [guydavis/machinaris#38]
# Summary / Dashboard
- Show Farming Plots
- Total Size of Plots
- Data storage left
- Network sync status

# Plotting
- Percentage tracker
- History with stats (time taken etc.)

**Comment by guydavis** [comment]
Nice suggestions.  Hopefully soon...

**Comment by guydavis** [comment]
Many of these are now available in test release. Working on others currently. Will be available soon in full release.

**Comment by guydavis** [comment]
Very happy to close this oldest open issue with the release of [v0.6.7](https://github.com/guydavis/machinaris/releases/tag/0.6.7).  I finally found time to add a Plotting Speed chart to the Plotting page, showing time in minutes for each k-size, across all plotting workers:

![20211201_200005](https://user-images.githubusercontent.com/12936/144631033-75a35319-0e4c-4394-b5b7-dcedf0611879.png)
