### ISSUE TITLE
Locked plotting job

### ISSUE THREAD

**Issue by cani1989** [guydavis/machinaris#384]
Version 0.6.2

Dead-locked plotting job:
![image](https://user-images.githubusercontent.com/622305/139649845-9106110c-afcf-4709-abd2-27b69c9f24cb.png)

When I try to Kill this job, then I get an error page with internal error:
![image](https://user-images.githubusercontent.com/622305/139649928-7e7d9c92-0bf9-430d-ad4a-32deed434663.png)

It happened after upgrading to the new version and I had a job running, which cannot be removed now.

**Comment by guydavis** [comment]
Hi, thanks for upgrading your Unraid to latest v0.6.2 release of Machinaris, following [the upgrade guide](https://github.com/guydavis/machinaris/wiki/Unraid#how-do-i-update-from-v05x-to-v060-with-fork-support).  It looks like there may be some stale status info left behind.  Please try the following:

1. Stop the Machinaris container
2. Remove file on Unraid host OS: `/mnt/user/appdata/machinaris/machinaris/dbs/machinaris.db`
3. Start the Machinaris container
4. Wait about 10 minutes for only active status to re-populate.

Hope this helps!

**Comment by cani1989** [comment]
Hi, thanks! It worked.
