### ISSUE TITLE
Forks: Support STOR

### ISSUE THREAD

**Issue by easleycorey** [guydavis/machinaris#387]
Fork support for STOR before Venidium but after staicoin

seems to be holding between 2 and 4 cents and the block is for 4 coins.

https://stor.network/

https://chiaforkscalculator.com/stor

List and info of forks I suggest:
https://docs.google.com/spreadsheets/d/1ttIK-TQwwWeY4XarapjKAYJIgDJ5Kk9yjvBPLIlrpdg/edit#gid=

**Comment by guydavis** [comment]
When checking with our [Discord ](https://discord.gg/mX4AtMTt87) in the #feature-ideas channel about which fork to support next, it looks like Dogechia, Greendoge, and Stor are currently the leading contenders.

![image](https://user-images.githubusercontent.com/12936/140570330-679c28eb-e732-4c83-95f5-bdd9c3586bff.png)

Voting is still open, and I'll keep adding supported forks in Machinaris as time allows.

**Comment by easleycorey** [comment]
O I see the voting is mainly in discord. Was wondering why it felt slow on the github request haha.

**Comment by guydavis** [comment]
Thanks!  Stor was a leading request so it's coming in the next release.  Currently available in develop stream.

![image](https://user-images.githubusercontent.com/12936/140787053-03ecca0d-d5f6-4d5b-ac9c-2cfac361a215.png)

**Comment by guydavis** [comment]
This is now available in v0.6.4.  Thanks again for the suggestion.
