### ISSUE TITLE
Fork: Support for Cactus

### ISSUE THREAD

**Issue by guydavis** [guydavis/machinaris#389]
As requested by Dommer.

**Comment by dominick01234** [comment]
Thank you. All modifications to the application were made so that Cactus can be run. It only now needs the Cactus repository added to your Docker Images Container (image: ghcr.io/guydavis/machinaris-cactus:latest). Thank you, Dommer

**Comment by guydavis** [comment]
When checking with our [Discord ](https://discord.gg/mX4AtMTt87) in the #feature-ideas channel about which fork to support next, it looks like Dogechia, Greendoge, and Stor are currently the leading contenders.

![image](https://user-images.githubusercontent.com/12936/140570330-679c28eb-e732-4c83-95f5-bdd9c3586bff.png)

Voting is still open, and I'll keep adding supported forks in Machinaris as time allows.

**Comment by dominick01234** [comment]
@guydavis I just pointed Farmers from my forum to your Poll as well. Hopefully my fork to your tool will save you time in adding Cactus. I've also been spreading the word on your solution as I think it is very elegant. Thanks, Dommer

**Comment by guydavis** [comment]
Thanks!  Support is coming soon.  Currently in Machinaris `:develop` stream: 

![image](https://user-images.githubusercontent.com/12936/140786478-464eb900-a0fd-4f81-829e-9d52a71eb7d7.png)

**Comment by guydavis** [comment]
This is now available in v0.6.4. Thanks for the suggestion!
