### ISSUE TITLE
Simple Login Page

### ISSUE THREAD

**Issue by cani1989** [guydavis/machinaris#39]
Just simple username and password that can be set in docker or settings.

**Comment by guydavis** [comment]
Sorry, the best approach for this is to [proxy access to Machinaris through something like Nginx](https://github.com/guydavis/machinaris/wiki/Nginx), which has multiple mechanisms for adding authentication.  Give Nginx a try for this purpose.  Relevant [FAQ](https://github.com/guydavis/machinaris/wiki/FAQ#why-doesnt-machinaris-offer-an-authentication-mechanism-to-allow-logins).
