### ISSUE TITLE
Can not save settings farmer when fullnode is not first worker

### ISSUE THREAD

**Issue by StefVos** [guydavis/machinaris#399]
Can not open or save Settings - Farmer when first worker is not a farmer or fullnode.
After adding a couple of new plotter workers to my fullnode i noticed that i could no longer update the farmer from the settings menu. 
The cause for this seems te be that the selectors for "Worker" and "Fork" are populated from all workers, before a selection is made the first worker in alphabetical order gets selected, in my case this worker is a plotter not a farmer causing the issue.

**To Reproduce**
After adding a worker with a hostname that preceeds the hostname of the fullnode the Settings -> Farmer menu no longer works.

**System setup:**
 - OS: Alpine Linux v3.14
 - Docker version 20.10.9
 - Machinaris branch: main
 - Machinaris version number 0.6.3

**Config**
<details><summary>full configuration</summary>

```
# paste your Docker run or Docker compose here
```

</details>

**Additional context & screenshots**

Workaround: make sure the hostname of a farmer or fullnode is the first.
In **/web/routes.py settings_farming** calls **find_selected_worker** that returns the first worker from a list of all workers ( **/web/action/workers.py** load_worker_summary) when no hostname is given.

**Comment by efnats** [comment]
Another workaround is to add any other worker that has a corresponding blockchain set as the worker you are trying to save the config from.

**Comment by StefVos** [comment]
Thanks !

**Comment by guydavis** [comment]
Thanks @ both for the report here.  I spent some time this week testing various controller/worker/fork scenarios on multiple machines.  I *think* that I have this working properly now.  Currently in the [`:test` images](https://github.com/guydavis/machinaris/wiki/Releases#release-streams). Will be available in next release.

**Comment by guydavis** [comment]
This has now been released as v0.6.4.  Let me know if the problem recurs in this latest release and I'll re-open the issue.  Thanks again for the report.
