### ISSUE TITLE
API not accessable? Retruns 404

### ISSUE THREAD

**Issue by Nold360** [guydavis/machinaris#403]
**Describe the bug**

I tried to access the API using browser, postman & curl via Ingress & from inside the container, but all i get is a 404.

I tried uris like: /ping, /stats, /stats/, /api/stats, /api/v1/stats, ... nothing works

**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Set up config with default values
2. Run Machinaris
3. `curl ${machinaris}/ping` 
4. See 404 error

**Expected behavior**

Pong!

**System setup:**
 - OS: Debian 11
 - Machnaris running on Kubernetes / K3s behind nginx ingress - container image is latest 
 - Machinaris branch: main
 - Machinaris version number: 0.6.3

**Comment by guydavis** [comment]
Hi, thanks for checking out the Machinaris [REST API](https://github.com/guydavis/machinaris#rest-api).  We welcome [contributions](https://github.com/guydavis/machinaris/wiki/Contributing) to the project!

Looking at your command above, its not clear what you are replacing `${machinaris}` with.  Please ensure you attempt to connect on the API port of tcp/8927.  See the Postman [collection](https://github.com/guydavis/machinaris/blob/main/api/machinaris.postman_collection.json) and [environment](https://github.com/guydavis/machinaris/blob/main/api/machinaris.postman_environment.json) for details.

Please let me know if this addresses your question.

**Comment by Nold360** [comment]
${machinaris} would either be `https://my-machinaris.domain` for the reverse-proxy / ingress. Or `http://localhost:8927` from the container itself. I imported your collection & setup the env in postman and got the same results.

**Comment by guydavis** [comment]
Sorry to hear you're still having a trouble.  Here's a screenshot to better explain.  From in the container:

![image](https://user-images.githubusercontent.com/12936/141186407-3d30a4a2-a8a4-4023-b2a2-f9afcdc0924a.png)

Could be the address being bound to on your host.  Please try `netstat -an | grep 8927` on your host OS, to ensure the port is bound and exposed.

![image](https://user-images.githubusercontent.com/12936/141186718-a5e665ae-7996-4cb4-a34d-f7c5591a97a5.png)


Here's me trying http://localhost:8927/ping/ from the Host OS (Unraid), when using Docker bridge networking:

![image](https://user-images.githubusercontent.com/12936/141186664-e333b8f4-81fd-4c63-bbe3-e4fa0bfe7d77.png)

**Comment by Nold360** [comment]
alright, it's working from localhost. Oh, and i missed that it's on a different port then the webinterface, no wonder it's not working from my ingress.... so nvm. 

PS: but it would be really cool to get "plotman prometheus" stats via api :) I might have a look if i can integrate that somehow
