### ISSUE TITLE
Display balance for different wallet

### ISSUE THREAD

**Issue by abien** [guydavis/machinaris#405]
When using the cold wallet the current display of balance becomes sort of obsolete since all rewards will be transfered to the cold wallet instead of the farming wallet.

I suggest to make the display configurable somehow.

**Comment by guydavis** [comment]
The display (and sum) of cold wallet balances is now available in the current `:test` images.  Will be in the upcoming v0.6.5 release.  Thanks again for the suggestion.

**Comment by guydavis** [comment]
Good day!  [Version 0.6.5](https://github.com/guydavis/machinaris/releases/tag/0.6.5) has now been released.
