### ISSUE TITLE
Chives Support for Docker/Synology Foxy Pool

### ISSUE THREAD

**Issue by maletazul** [guydavis/machinaris#419]
Hi,

as request here the problem i get trying to compile foxy add-on inside Chives.docker on synology:

sudo dpkg -i chives-blockch
ain_1.1.906-og-pooling-1.0.3_amd64.deb                                          
Selecting previously unselected package chives-blockchain.                      
(Reading database ... 63968 files and directories currently installed.)         
Preparing to unpack chives-blockchain_1.1.906-og-pooling-1.0.3_amd64.deb ...    
Unpacking chives-blockchain (1.1.906) ...                                       
dpkg: dependency problems prevent configuration of chives-blockchain:           
 chives-blockchain depends on libgtk-3-0; however:                              
  Package libgtk-3-0 is not installed.                                          
 chives-blockchain depends on libnotify4; however:                              
  Package libnotify4 is not installed.                                          
 chives-blockchain depends on libnss3; however:                                 
  Package libnss3 is not installed.                                             
 chives-blockchain depends on libxtst6; however:                                
  Package libxtst6 is not installed.                                            
 chives-blockchain depends on xdg-utils; however:                               
  Package xdg-utils is not installed.                                           
 chives-blockchain depends on libatspi2.0-0; however:                           
  Package libatspi2.0-0 is not installed.                                       
 chives-blockchain depends on libdrm2; however:                                 
  Package libdrm2 is not installed.                                             
 chives-blockchain depends on libgbm1; however:                                 
  Package libgbm1 is not installed.                                             
 chives-blockchain depends on libxcb-dri3-0; however:                           
  Package libxcb-dri3-0 is not installed.                                       
 chives-blockchain depends on kde-cli-tools | kde-runtime | trash-cli | libglib2
.0-bin | gvfs-bin; however:                                                     
  Package kde-cli-tools is not installed.                                       
  Package kde-runtime is not installed.                                         
  Package trash-cli is not installed.                                           
  Package libglib2.0-bin is not installed.                                      
  Package gvfs-bin is not installed.                                            
                                                                                
dpkg: error processing package chives-blockchain (--install):                   
 dependency problems - leaving unconfigured                                     
Errors were encountered while processing:                                       
 chives-blockchain                      

Addon Chives Foxy Pool Releases:
https://github.com/foxypool/chives-blockchain/releases

Addicional config.yaml to add 👍 
https://docs.foxypool.io/proof-of-spacetime/foxy-pool/pools/chives-og/getting-started/

If possible was great, since i can use machinaris to my full farmers

**Comment by OlivierGaland** [comment]
Hello,

I'm also interested by this enhancement, if it can help i did the following entries on a fullnode chives container : 

Log as root on container (I'm using portainer on the docker box to manage my containers)

dpkg -i chives-blockchain_1.2.11-og-pooling-1.0.3_amd64.deb 
(*** show dependencies errors ***)
apt-get -f install 
(lots of things installed)
dpkg -i chives-blockchain_1.2.11-og-pooling-1.0.3_amd64.deb
(command is now successfull)

Stop + Start container

Unfortunately this seems not to work (I do not see the "OG pool" inside the debug.log) but i'm not an expert in docker container so i did not yet understood why it does not work.

Regards,
Olivier

**Comment by centrd** [comment]
I too would like to use the modified Foxy pool binary for OG pooling.
Are there any workarounds?

**Comment by fufar** [comment]
Any news on this? I want migrate from foxy chives client to machinaris, now if i understand right - it is not possible

**Comment by guydavis** [comment]
Thanks for the PR! Please try out this [image](https://github.com/guydavis/machinaris/pkgs/container/machinaris-chivesfoxy): `machinaris-chivesfoxy:develop`, to be used in place of the regular `machinaris-chives:develop`.  All other configuration is unchanged.  

Let me know how it goes as I'm not part of this pool so can't test.  Feel free to post problems here, especially if you have suggested solutions. :)

**Comment by fufar** [comment]
Ok 
container at least started, need few days for tests

**Comment by fufar** [comment]
Afther 3 days test: all seems ok, foxypool accept mining

**Comment by guydavis** [comment]
Available now in the Machinaris [v0.8.7 release](https://github.com/guydavis/machinaris/releases/tag/0.8.7).
