### ISSUE TITLE
Worker cannot connect to host for new fork Cactus and Stor - new install of 0.6.4

### ISSUE THREAD

**Issue by hadhud** [guydavis/machinaris#421]
**Describe the bug**
Worker cannot connect to host for new fork Cactus and Stor, working of all the other forks. New install of 0.6.4 for both the fullnode and worker.

**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Install new fullnode 0.6.4.
2. Install new worker with 0.6.4
3. Add all forks including Cactus and Stor
4. See the error in Alerts/chiadog as harvester offline or in Machinaris worker log for Cactus or Stor. All other forks are online and working.

**Expected behavior**
Cactus fork error in Machinaris log:
"2021-11-17T09:27:12.943 harvester harvester_server        : INFO     Cannot connect to host 192.168.1.192:11447 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1129)')]"

Stor fork error in Machinaris log:
"2021-11-17T09:36:06.697 harvester harvester_server        : INFO     Cannot connect to host 192.168.1.192:8337 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1129)')]"

**System setup:**
 - OS: Ubuntu 20.04.3 LTS
 - Docker version number: 20.10.10
 - Machinaris branch: main
 - Machinaris version number: 0.6.4

**Config**
<details><summary>full configuration</summary>

```
# paste your Docker run or Docker compose here
```
version: '3.7'
services:

    machinaris-cactus:
        image: ghcr.io/guydavis/machinaris-cactus:latest
        container_name: machinaris-cactus
        hostname: super-on-v2
        restart: always
        volumes:
            - ~/.machinaris-cactus:/root/.chia
            - "/mnt/storage:/plots1"
            - "/mnt/temp1:/plotting"
        environment:
            - TZ=Europe/Stockholm
            - farmer_address=192.168.1.192
            - farmer_port=11447
            - mode=harvester
            - controller_host=192.168.1.192
            - controller_api_port=8927
            - worker_address=192.168.1.97
            - worker_api_port=8936
            - plots_dir=/plots1
            - blockchains=cactus
        ports:
            - 8936:8936

    machinaris:
        image: ghcr.io/guydavis/machinaris:latest
        container_name: machinaris
        hostname: super-on-v2
        restart: always
        volumes:
            - ~/.machinaris:/root/.chia
            - "/mnt/storage:/plots1"
            - "/mnt/temp1:/plotting"
        environment:
            - TZ=Europe/Stockholm
            - farmer_address=192.168.1.192
            - farmer_port=8447
            - mode=harvester
            - controller_host=192.168.1.192
            - controller_api_port=8927
            - worker_address=192.168.1.97
            - worker_api_port=8927
            - plots_dir=/plots1
            - blockchains=chia
        ports:
            - 8926:8926
            - 8927:8927

    machinaris-chives:
        image: ghcr.io/guydavis/machinaris-chives:latest
        container_name: machinaris-chives
        hostname: super-on-v2
        restart: always
        volumes:
            - ~/.machinaris-chives:/root/.chia
            - "/mnt/storage/chives:/plots1"
            - "/mnt/temp1:/plotting"
        environment:
            - TZ=Europe/Stockholm
            - farmer_address=192.168.1.192
            - farmer_port=9647
            - mode=harvester
            - controller_host=192.168.1.192
            - controller_api_port=8927
            - worker_address=192.168.1.97
            - worker_api_port=8931
            - plots_dir=/plots1
            - blockchains=chives
        ports:
            - 8931:8931

    machinaris-flax:
        image: ghcr.io/guydavis/machinaris-flax:latest
        container_name: machinaris-flax
        hostname: super-on-v2
        restart: always
        volumes:
            - ~/.machinaris-flax:/root/.chia
            - "/mnt/storage:/plots1"
            - "/mnt/temp1:/plotting"
        environment:
            - TZ=Europe/Stockholm
            - farmer_address=192.168.1.192
            - farmer_port=6885
            - mode=harvester
            - controller_host=192.168.1.192
            - controller_api_port=8927
            - worker_address=192.168.1.97
            - worker_api_port=8928
            - plots_dir=/plots1
            - blockchains=flax
        ports:
            - 8928:8928

    machinaris-flora:
        image: ghcr.io/guydavis/machinaris-flora:latest
        container_name: machinaris-flora
        hostname: super-on-v2
        restart: always
        volumes:
            - ~/.machinaris-flora:/root/.chia
            - "/mnt/storage:/plots1"
            - "/mnt/temp1:/plotting"
        environment:
            - TZ=Europe/Stockholm
            - farmer_address=192.168.1.192
            - farmer_port=18647
            - mode=harvester
            - controller_host=192.168.1.192
            - controller_api_port=8927
            - worker_address=192.168.1.97
            - worker_api_port=8932
            - plots_dir=/plots1
            - blockchains=flora
        ports:
            - 8932:8932

    machinaris-hddcoin:
        image: ghcr.io/guydavis/machinaris-hddcoin:latest
        container_name: machinaris-hddcoin
        hostname: super-on-v2
        restart: always
        volumes:
            - ~/.machinaris-hddcoin:/root/.chia
            - "/mnt/storage:/plots1"
            - "/mnt/temp1:/plotting"
        environment:
            - TZ=Europe/Stockholm
            - farmer_address=192.168.1.192
            - farmer_port=28447
            - mode=harvester
            - controller_host=192.168.1.192
            - controller_api_port=8927
            - worker_address=192.168.1.97
            - worker_api_port=8930
            - plots_dir=/plots1
            - blockchains=hddcoin
        ports:
            - 8930:8930

    machinaris-nchain:
        image: ghcr.io/guydavis/machinaris-nchain:latest
        container_name: machinaris-nchain
        hostname: super-on-v2
        restart: always
        volumes:
            - ~/.machinaris-nchain:/root/.chia
            - "/mnt/storage:/plots1"
            - "/mnt/temp1:/plotting"
        environment:
            - TZ=Europe/Stockholm
            - farmer_address=192.168.1.192
            - farmer_port=38447
            - mode=harvester
            - controller_host=192.168.1.192
            - controller_api_port=8927
            - worker_address=192.168.1.97
            - worker_api_port=8929
            - plots_dir=/plots1
            - blockchains=nchain
        ports:
            - 8929:8929

    machinaris-staicoin:
        image: ghcr.io/guydavis/machinaris-staicoin:latest
        container_name: machinaris-staicoin
        hostname: super-on-v2
        restart: always
        volumes:
            - ~/.machinaris-staicoin:/root/.chia
            - "/mnt/storage:/plots1"
            - "/mnt/temp1:/plotting"
        environment:
            - TZ=Europe/Stockholm
            - farmer_address=192.168.1.192
            - farmer_port=1692
            - mode=harvester
            - controller_host=192.168.1.192
            - controller_api_port=8927
            - worker_address=192.168.1.97
            - worker_api_port=8934
            - plots_dir=/plots1
            - blockchains=staicoin
        ports:
            - 8934:8934

    machinaris-stor:
        image: ghcr.io/guydavis/machinaris-stor:latest
        container_name: machinaris-stor
        hostname: super-on-v2
        restart: always
        volumes:
            - ~/.machinaris-stor:/root/.chia
            - "/mnt/storage:/plots1"
            - "/mnt/temp1:/plotting"
        environment:
            - TZ=Europe/Stockholm
            - farmer_address=192.168.1.192
            - farmer_port=8337
            - mode=harvester
            - controller_host=192.168.1.192
            - controller_api_port=8927
            - worker_address=192.168.1.97
            - worker_api_port=8935
            - plots_dir=/plots1
            - blockchains=stor
        ports:
            - 8935:8935

</details>

**Additional context & screenshots**

**Comment by Enissay** [comment]
Same for my Harvester, but SSL error is showing for Cactus, Stor and Chia. All others are fine

**Comment by guydavis** [comment]
Sorry to hear that.  For Cactus and Stor harvester startup only, please change to ':test` from `:latest` on end of image line in the New Worker generated `docker-compose.yml`, then execute the following:
```
docker-compose stop
rm -rf ~/.machinaris/machinaris-cactus/farmer_ca
rm -rf ~/.machinaris/machinaris-stor/farmer_ca
docker-compose pull
docker-compose up -d --force-recreate
```
This will pull a slightly newer image that will automatically retrieve the correct certificates.

**Comment by guydavis** [comment]
> Same for my Harvester, but SSL error is showing for Cactus, Stor and Chia. All others are fine

For Cactus and Stor harvesters, please see my [response here](https://github.com/guydavis/machinaris/issues/421#issuecomment-971740908).

For Chia harvesters, please ensure you have recently clicked the New Worker button on the Workers page of the Machinaris WebUI before attempting to (re)start the Machinaris Chia harvester.

**Comment by hadhud** [comment]
Thanks for the quick response and an overall great work with Machinaris!

**Comment by Enissay** [comment]
@guydavis I applied both fixes and the Chia one magically worked.
Before checking on the other one all the sudden I have `Internal Server Error`.

Here's the error from `.machinaris/machinaris/logs/webui.log`:
```log
2021-11-17 18:39:49 [110] [INFO] 192.168.1.102 - - [17/Nov/2021:18:39:49 +0100] "GET /index HTTP/1.1" 500 290 "http://192.168.1.133:8926/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
2021-11-17 18:39:49 [110] [INFO] 192.168.1.102 - - [17/Nov/2021:18:39:49 +0100] "GET /favicon.ico HTTP/1.1" 304 0 "http://192.168.1.133:8926/index" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
2021-11-17 18:41:05 [111] [INFO] Failed to find presence of public wallet key due to module 'posixpath' has no attribute 'exist'
2021-11-17 18:41:05 [111] [ERROR] Exception on /index [GET]
Traceback (most recent call last):
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/machinaris/web/routes.py", line 32, in index
    workers = worker.load_worker_summary()
  File "/machinaris/web/actions/worker.py", line 45, in load_worker_summary
    return WorkerSummary(workers)
  File "/machinaris/web/models/worker.py", line 70, in __init__
    self.set_worker_attributes(worker)
  File "/machinaris/web/models/worker.py", line 80, in set_worker_attributes
    other_versions += "Bladebit: " + config['bladebit_version'] + "<br/>"
TypeError: can only concatenate str (not "NoneType") to str
2021-11-17 18:41:05 [111] [ERROR] Exception on /index [GET]
Traceback (most recent call last):
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/machinaris/web/routes.py", line 32, in index
    workers = worker.load_worker_summary()
  File "/machinaris/web/actions/worker.py", line 45, in load_worker_summary
    return WorkerSummary(workers)
  File "/machinaris/web/models/worker.py", line 70, in __init__
    self.set_worker_attributes(worker)
  File "/machinaris/web/models/worker.py", line 80, in set_worker_attributes
    other_versions += "Bladebit: " + config['bladebit_version'] + "<br/>"
TypeError: can only concatenate str (not "NoneType") to str

```

**Comment by Enissay** [comment]
Any suggestion here please. I am hoping to get to before even with the issues I had, I wont complain xD

**Comment by guydavis** [comment]
> Any suggestion here please. I am hoping to get to before even with the issues I had, I wont complain xD

Sorry, I didn't follow this sentence, but I think you are requesting an escalation in the urgency of your concerns.  What have you tried so far to fix it yourself?  For example, have you tried [upgrading](https://github.com/guydavis/machinaris/wiki/Releases#release-streams) from the current release (v0.6.4) to the test release (upcoming v0.6.5).  If yes,  how long ago did you last try to pull `:test` images?  

Please ensure your next report (here) includes exactly the problem you are encountering when trying to connect Cactus and Stor harvesters using the most recent `:test` images.  If instead you are reporting a new complaint, please open a new Issue, rather than piggybacking on this one.  Thanks!

**Comment by Enissay** [comment]
@guydavis I applied your fix immediately on the Harvester after you message yesterday (using `:test` on both Stor & Cactus). Then, on the farmer/FullNode, while I was refreshing the pages to check if the fix worked, after a while I got the `Internal Server Error` and the webUI is inaccessible now. 

I am not sure if that is linked to the changes I made, else I can start a new issue, what I have is:
- The `.machinaris/machinaris/logs/apisrv.log` doesnt show any errors and event seems to going as usual
- The `.machinaris/machinaris/logs/webui.log` throws the error I shared above when refreshing the WebUI: It starts loading before it shows:
```html
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by guydavis** [comment]
> @guydavis I applied your fix immediately on the Harvester after you message yesterday (using `:test` on both Stor & Cactus). Then, on the farmer/FullNode, while I was refreshing the pages to check if the fix worked, after a while I got the `Internal Server Error` and the webUI is inaccessible now.
> 
> I am not sure if that is linked to the changes I made, else I can start a new issue, what I have is:
> 
> * The `.machinaris/machinaris/logs/apisrv.log` doesnt show any errors and event seems to going as usual
> * The `.machinaris/machinaris/logs/webui.log` throws the error I shared above when refreshing the WebUI: It starts loading before it shows:
> 
> ```
> Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> ```

Hi, thanks for testing! Sounds like you're out-of-date on `:test` now which changes frequently.  As per the [upgrade guide](https://github.com/guydavis/machinaris/wiki/Releases#release-streams), please do the following:

```
docker-compose stop
docker-compose rm -f 
docker-compose pull
docker-compose up -d --force-recreate
```

**Comment by guydavis** [comment]
Good day!  [Version 0.6.5](https://github.com/guydavis/machinaris/releases/tag/0.6.5) has now been released.
