### ISSUE TITLE
Forks: Support AedgeCoin

### ISSUE THREAD

**Issue by rymdluo** [guydavis/machinaris#433]
Hi, I am the project owner of AedgeCoin and would like to see about adding support for it on machinaris.

Here are some details about the project:

Launched: 2021-10-17
Name of coin/Ticker Symbol: Aedge/AEC
Website: aedgecoin.com
ChiaForum Thread: https://chiaforum.com/t/aedgecoin-is-a-chiafork-with-a-focus-on-algotrading/14250
Newsletter: http://newsletter.aedgecoin.com/
Github: https://github.com/AedgeCoin/aedge-blockchain

**Comment by guydavis** [comment]
This blockchain didn't get enough votes last time.  [Voting has just opened](https://discord.com/channels/842422792593866782/845378554878754857/951526113396547614) again on the next blockchain to support however.  We'll see how this one does this round.

**Comment by guydavis** [comment]
Closing as no updates to this blockchain since last fall.
