### ISSUE TITLE
Chia Plots Check "Option"

### ISSUE THREAD

**Issue by mdrummer68** [guydavis/machinaris#450]
Would you add the ability to disable "chia plots check"?  Not all situations require it, and having the option to disable it would be preferred.

**Comment by guydavis** [comment]
No problem, use `plots_check_analyze_skip` environment variable.  Set value `true`.  Already available in `:test` images for v0.6.7.  Released soon.

**Comment by mdrummer68** [comment]
Great to hear.  Appreciate all your hard work.  Thanks for the quality apps.
