### ISSUE TITLE
[feature request] - Choice between plotman, Swar plot manager,  Harry plotter.

### ISSUE THREAD

**Issue by gabiroli** [guydavis/machinaris#47]
It would be nice to have a choice between plotman,  Swar plot manager, and harry plotter.  So that everyone can use whichever they prefer.   Or they can switch between plot managers if one of them comes out with a new feature or just more reliable.

**Comment by cm86** [comment]
i would recommend Swar... and would be very happy to support you with the implementation...

**Comment by carlosvsilva** [comment]
Also don't forget the excellent plotng :)

**Comment by guydavis** [comment]
Closing as we'll continue using Plotman for now.  Their v0.5 has just been released.
