### ISSUE TITLE
Maize Cold Wallet not show coins

### ISSUE THREAD

**Issue by robertbigk** [guydavis/machinaris#491]
Unraid config 
Maize wallet full sync no error in log 

send 1 XMZ on machinaris status not updated two days
On windows that same address status updated show 1 coin what I send.

Correct should be 2 on cold wallet 1
![mstsc_mutiNGOMzO](https://user-images.githubusercontent.com/34956477/145515929-15d7ae18-03bd-46d6-8e35-dbf10d6fb791.png)
![msedge_QhQrgpPcHt](https://user-images.githubusercontent.com/34956477/145515951-4a7444d5-2efe-4b0a-9926-9bd6720e2f1f.png)

**Comment by guydavis** [comment]
Machinaris [version 0.8.0](https://github.com/guydavis/machinaris/releases/tag/0.8.0) has now been released with better cold wallet tracking.  Thanks!
