### ISSUE TITLE
New Feature - Disk Health Monitoring! 

### ISSUE THREAD

**Issue by k2skaterii** [guydavis/machinaris#494]
Seeing how Machinaris supports farming multiple "hard drive based" cryptos...  Seems like adding a tool that would compliment Machinaris nicely would be a Disk Health monitoring tool.

With 18 plot storage disks + 1 boot disk I've got a relatively small number of drives... Even with 19 drives identifying issues early, hopefully before SMART flags a disk a failing, is not easy.  

For Example - I bought 5 x 4TB $50 specials off eBAY last DEC.  They came with a 1 year warranty.  One of the disks started throwing errors back in FEB.  Another disk has some not so great statistics. SMART says these disks are healthy, while GSMARTCONTROL highlights some of the detailed output in RED.  Last I checked RED is bad!  The EBay Seller approved my RMA request based on the SMARTCTL output and will be sending me 2 new white label drives.  I'll attach some screen shots from these drives before I pull them out.  

Almost wanna say this is a requirement...  The solution used here should have the ability to store and display historical data related to the drives it is monitoring.  What data needs to be stored?  How should it be displayed?  I can provide several examples of output from SMARTCTL that I saved for the same device at different points this year.  Identifying things that have changed VS things that are not good but not getting worse - is a very manual task.  Shouldn't be hard to come up with something that is an improvement over manually analyzing multiple docs for each drive!

This drive failed in the first month - I've just been lazy.  I'm not sure if the stats or the Errors have changed since they first caught my attention.  Issues observed included plots that failed to move from this drive to another along with occasional challenge responses over 60 seconds.
<img width="645" alt="SDB_Stats" src="https://user-images.githubusercontent.com/87842648/145699647-1385ce39-5fec-4f99-a7d8-75505d9512b8.PNG">

<img width="647" alt="SDB_Errors" src="https://user-images.githubusercontent.com/87842648/145699651-41b1d135-5770-44a8-9aec-7c4187882cb4.PNG">

This drive never had any performance issues that I remember.  But, if RED is BAD and GSMARTCONTROL highlights these statistics as RED... I didn't want to ignore!  
<img width="643" alt="SDA_Stats_1" src="https://user-images.githubusercontent.com/87842648/145699666-9359a4aa-8d15-4068-9f78-afb07e69ea36.PNG">

<img width="637" alt="SDA_Issues_1" src="https://user-images.githubusercontent.com/87842648/145699668-63667489-272e-4758-9694-d47541fdc2dd.PNG">

Full Disclosure - This is not something I thought of on my own... Jonmichael Hands (Chia's VP Storage Business Dev) uploaded a video to YouTube on Nov 18th, "Chia farming - How Hard Drives fail!", linked below.  In that video he discussed hard drive failures, using the SMARTCTL util, interpreting the SMARTCTL output along with DEMO'ing a tool he had found on GitHub called SCRUTINY.
https://www.youtube.com/watch?v=SN6REW1VuPc

**Comment by k2skaterii** [comment]
I've been on the shit end of the stick when "the good idea fairy waved her wand" in the past... unclear requirements are almost as bad as impossible requirements!

GOOD - FAST - CHEAP.  You can pick 2 and only 2.  Pick your poison!

You may have guessed this - but I'm not someone you would accuse of being an active developer on GitHub, or anywhere else.  BUT I wasn't kidding when I said that I am willing to help with my disk monitoring enhancement request! 

So - what can I do to help get the ball rolling in relation to my "good idea"?

**Comment by efnats** [comment]
https://github.com/guydavis/machinaris/issues/291

**Comment by augustynr** [comment]
try this:
`version: "2.1"
services:
  scrutiny:
    image: analogj/scrutiny
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - SCRUTINY_API_ENDPOINT=http://YOUR-DOCKER-IP:8080
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
    volumes:
      - /root/.scrutiny:/config
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
      - /dev/sdf:/dev/sdf
      - /dev/sdg:/dev/sdg
      - /dev/sdh:/dev/sdh
      - /dev/sdi:/dev/sdi
      - /dev/sdj:/dev/sdj
      - /dev/sdk:/dev/sdk
      - /dev/sdl:/dev/sdl
      - /dev/sdm:/dev/sdm
      - /dev/sdn:/dev/sdn
      - /dev/sdo:/dev/sdo
      - /dev/sdp:/dev/sdp
      - /dev/sdq:/dev/sdq
      - /dev/sdr:/dev/sdr
      - /dev/sds:/dev/sds
      - /dev/sdt:/dev/sdt
      - /dev/sdu:/dev/sdu
      - /dev/sdv:/dev/sdv
      - /dev/sdw:/dev/sdw
      - /dev/sdx:/dev/sdx
      - /dev/sdy:/dev/sdy
      - /dev/sdz:/dev/sdz

      - /dev/sdaa:/dev/sdaa
      - /dev/sdab:/dev/sdab
      - /dev/sdac:/dev/sdac
      - /dev/sdad:/dev/sdad
      - /dev/sdae:/dev/sdae
      - /dev/sdaf:/dev/sdaf
      - /dev/sdag:/dev/sdag
      - /dev/sdah:/dev/sdah
      - /dev/sdai:/dev/sdai
      - /dev/sdaj:/dev/sdaj
      - /dev/sdak:/dev/sdak
      - /dev/sdal:/dev/sdal
      - /dev/sdam:/dev/sdam
      - /dev/sdan:/dev/sdan
      - /dev/sdao:/dev/sdao
      - /dev/sdap:/dev/sdap
      - /dev/sdaq:/dev/sdaq
      - /dev/sdar:/dev/sdar
      - /dev/sdas:/dev/sdas
      - /dev/sdat:/dev/sdat
      - /dev/sdau:/dev/sdau
      - /dev/sdav:/dev/sdav
      - /dev/sdaw:/dev/sdaw
      - /dev/sdax:/dev/sdax
      - /dev/sday:/dev/sday
      - /dev/sdaz:/dev/sdaz
      
      - /dev/sdba:/dev/sdba
      - /dev/sdbb:/dev/sdbb
      - /dev/sdbc:/dev/sdbc
      - /dev/sdbd:/dev/sdbd
      - /dev/sdbe:/dev/sdbe
      - /dev/sdbf:/dev/sdbf
      - /dev/sdbg:/dev/sdbg
      - /dev/sdbh:/dev/sdbh
      - /dev/sdbi:/dev/sdbi
      - /dev/sdbj:/dev/sdbj
      - /dev/sdbk:/dev/sdbk
      - /dev/sdbl:/dev/sdbl
      - /dev/sdbm:/dev/sdbm
      - /dev/sdbn:/dev/sdbn
      - /dev/sdbo:/dev/sdbo
      - /dev/sdbp:/dev/sdbp
      - /dev/sdbq:/dev/sdbq
      - /dev/sdbr:/dev/sdbr
#      - /dev/sdbs:/dev/sdbs
#      - /dev/sdbt:/dev/sdbt
#      - /dev/sdbu:/dev/sdbu
#      - /dev/sdbv:/dev/sdbv
#      - /dev/sdbw:/dev/sdbw
#      - /dev/sdbx:/dev/sdbx
#      - /dev/sdby:/dev/sdby
#      - /dev/sdbz:/dev/sdbz
      
    restart: unless-stopped`

**Comment by k2skaterii** [comment]
Yesterday I pulled 2 drives out of my system, so I could ship them back to be replaced under a rock solid "EBay Warranty".  After they were pulled, 2 things happened annoyed me.

1.  The Scrutiny container did not launch when I booted the system up.  `docker start scrutiny` threw an error that explained why it didn't launch when the system booted.  
> Cannot start service scrutiny: error gathering device information while adding custom device "/dev/sds": no such file or directory 
 This was easy enough to resolve, just had to remove that disk from the docker-compose.yaml... Unfortunately that error rules out the option of using a config like the one suggested by [augustynr](https://github.com/guydavis/machinaris/issues/494#issuecomment-993098529)
 
2.  After adjusting the YAML to reflect the 2 disks that were removed, the container launched successfully - but the last week's worth of historical temperature data was missing.  I was hoping the data was still available, just wasn't being displayed in the web GUI yet.  Maybe it needed some time to process hysterical data and would show up sooner or later.  24 hours later, and that data is still not being displayed - probably not coming back automagically at this point.

**Comment by k2skaterii** [comment]
I was looking around to see what options exist out there today - I didn't copy off the smart kid's test when I was in school.  Now that I'm an adult, copying someone else's homework is not only allowed, it's encouraged!  

[Scrutiny ](https://github.com/AnalogJ/scrutiny)
The guy who has been working on Scrutiny says this in his [GitHub BIO ](https://github.com/AnalogJ): 

> I'm currrently working on a project called Scrutiny. Scrutiny is a Hard Drive health dashboard & monitoring solution, merging manufacturer provided S.M.A.R.T metrics with real-world failure rates. Here's a screenshot:
> My current goal is to reach 25 Github Sponsors, at which point I plan on open sourcing Scrutiny. So if you'd like early-access to kick the tires (& support open source developers like myself) please consider sponsoring me. 

[hdck](https://github.com/tomato42/hdck)
- Check your HDD and SSD by scanning it for hidden or latent bad sectors, diagnose problems with HDDs.

I haven't done much more than find it at this point.  First look, I think it does it's thing, produces output... then goes away till next time.  Doesn't appear to store hysterical data, and presents it's output as CLI output not a webGUI.

[HardDiskValidator](https://github.com/TalAloni/HardDiskValidator)
- https://github.com/TalAloni/HardDiskValidator

This tool looks like it was designed to be run "offline", using a bootable ISO or similar.  I don't know if it could be adapted to work online, inside a container... 

In addition to existing tools that I found on GITHUB, I also found a few Grafana dashboards.  
[S.M.A.R.T Dashboard](https://grafana.com/grafana/dashboards/13654)
S.M.A.R.T Dashboard looks promising, while it may not be turn key.
- General panel with detailed disk data: model, name, size, firmware, serial, etc
- Temperature panel with graphs and gauge bars
- Wear panel showing disk lifetime cycles counters
 
It looks like that dashboard is using a data collection script that I'm assuming runs VIA CRONJOB every XX Hours.   If that script is collecting the required data, storing the data to be displayed w/ Grafana at a later date... It would likely need some tweaks before it would work within a container.  

I am going to mess with S.M.A.R.T Dashboard tonight.  After I check a few other things off my todo list.

**Comment by guydavis** [comment]
Thanks everyone for all the details provided above.  I have [a start on an implementation](https://github.com/guydavis/machinaris/wiki/Drives) of this within the Machinaris development branch.

**Comment by efnats** [comment]
I love you!

**Comment by guydavis** [comment]
Next version (Machinaris 0.7.2) will now include an alert, sent out via Chiadog to your configured targets) of a SMARTCL status change of a drive from 'PASSED' to any other status, likely indicating a failure.

**Comment by guydavis** [comment]
This fix is now available in the [Machinaris v0.7.2 release](https://github.com/guydavis/machinaris/releases/tag/0.7.2) today. Thanks!
