### ISSUE TITLE
(Optional)mega-cmd can be added to base docker

### ISSUE THREAD

**Issue by raingggg** [guydavis/machinaris#496]
This is an optional improvement. 

After studying your mega-cmd changes, I thought a lot about the mega-setup script. Personally I would prefer moving mega-cmd setup script into base docker for following reasons:

Pros:
1. Improve setup speed for some locations -  good for those mega-cmd site access slow cases
2. Accelerate initial entry-point.sh deploy, since it has been installed on base docker

Cons:
1. Base docker image size might be a bit bigger - should be acceptable
2. Useless when it is not fullnode mode - similar as 1
3. Better blockchain db archives appear - we can remove it then

**Comment by guydavis** [comment]
Thanks for the feedback.  However, only the full-node containers may make use of the `mega-cmd` tools, other containers won't.  Also, I received very clear feedback that users wanted Docker images to be as small as possible, so I obliged [their request](https://github.com/guydavis/machinaris/issues/347).
