### ISSUE TITLE
Error response from daemon: manifest unknown

### ISSUE THREAD

**Issue by SametBasturkk** [guydavis/machinaris#509]
C:\Users\asus\Desktop\machinaris-0.6.7>docker-compose pull
[+] Running 0/10
 - machinaris-btcgreen Error                                                                                       1.2s
 - machinaris-flora Error                                                                                          1.2s
 - machinaris-stor Error                                                                                           1.2s
 - machinaris-flax Error                                                                                           1.2s
 - machinaris-hddcoin Error                                                                                        1.2s
 - machinaris-maize Error                                                                                          1.2s
 - machinaris Error                                                                                                1.2s
 - machinaris-shibgreen Error                                                                                      1.2s
 - machinaris-staicoin Error                                                                                       1.2s
 - machinaris-nchain Error                                                                                         1.2s
Error response from daemon: manifest unknown

I am getting this error. Compose successfully installed

**Comment by SametBasturkk** [comment]
same error with up -d

**Comment by guydavis** [comment]
Hi, the snippet above is not enough here to diagnosis the problem.   Please complete the template Issue form that you were presented with when you added this issue to Github.

**Comment by guydavis** [comment]
Actually, I think you may be trying to run `:latest`?  If so, for Shibgreen, please replace `:latest` with `:test` in your docker-compose.yml.  Thanks!

**Comment by guydavis** [comment]
Hi, any update on this issue?  Did you get it sorted out or do you have anything further to report?

**Comment by guydavis** [comment]
Latest release [v0.6.8](https://github.com/guydavis/machinaris/releases/tag/0.6.8) is out so closing this.  Thanks again!
