### ISSUE TITLE
Add Blockchain status summary table page

### ISSUE THREAD

**Issue by depasseg** [guydavis/machinaris#520]
As a user, having a tabular list of the status of all the blockchains would be very helpful.

Currently, on the Blockchains tab, a user must click on each blockchain to view the connection status. 

If there was a summary Blockchain status table (similar to the wallet page) that provides the blockchain status ("Syncing 536856/1352497"), time ("Wed Jul 07 2021 02:00:04 EDT"), and connections ("39") it would be easy to see at a glance if all blockchain containers are up and responding.   With the dust storms picking up and the amount of resources required to run all the blockchains on my server,  I find myself checking those datapoints frequently to monitor what's going on across all my blockchains (and restart containers as needed to re-establish sync).

**Comment by Doccy008** [comment]
It would also be nice if it showed if the wallet is in sync. And some red and green colours of course :)
