### ISSUE TITLE
Include external web resources [js/css] in docker image

### ISSUE THREAD

**Issue by Nold360** [guydavis/machinaris#537]
**Describe the request**
I would like to see all external javascript & css resource be included in the docker image, instead loaded from 3rd parties. Because:
1. I'm paranoid
2. machinaris ui keeps working without internet access of the client

**Additional comments**
Example of what I mean: 

https://github.com/guydavis/machinaris/blob/main/web/templates/base.html
```html
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" ...>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.css">
```

https://github.com/guydavis/machinaris/blob/main/web/templates/setup.html
```html
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" ...>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
```

**Comment by guydavis** [comment]
Sorry, Machinaris currently requires Internet access for all sorts of things including blockchain connectivity, API calls, and slimming the image (see #347).   A Internet-disconnected system does not seem feasible at this time.

**Comment by guydavis** [comment]
Revising my assessment as #541 PR makes clear this is only about [CDN resources](https://httptoolkit.tech/blog/public-cdn-risks/) served to a user's browser.  This has nothing to do with the absolute requirement of the Machinaris docker container to have Internet access on the backend (Chia farming).  I incorrectly conflated the two issues.

**Comment by guydavis** [comment]
Closing as [Machinaris version 0.6.9](https://github.com/guydavis/machinaris/releases/tag/0.6.9) has now been released.
