### ISSUE TITLE
There is bug when staincoin container start

### ISSUE THREAD

**Issue by Sagittarius** [guydavis/machinaris#538]
![reproduce](https://cdn.discordapp.com/attachments/849382899101859870/931117421652226078/unknown.png)

**Additional context & screenshots**

There is a code error in [/machinaris/main/scripts/forks/staicoin_launch.sh](https://raw.githubusercontent.com/guydavis/machinaris/main/scripts/forks/staicoin_launch.sh),the url to download certs from farmer should be "http://${farmer_address}:8934/certificates/?type=staicoin", **"http://${farmer_address}:8934/certificates/?type=stai"**

![screenshot](https://cdn.discordapp.com/attachments/849382899101859870/931119112652980284/unknown.png)

**Comment by guydavis** [comment]
Yes, this is an issue in the current release v0.6.8.  The [fix](https://github.com/guydavis/machinaris/commit/b6f644a4d6f183cb542795d9d08e5c0d8ab367f7) was made 15 days ago and has been available in the integration branch for a while now.  

Please review the Staicoin channel in the [Machinaris Discord](https://discord.gg/mX4AtMTt87), where you will find that running this blockchain is currently not recommended to various defects present in their latest release.

**Comment by Sagittarius** [comment]
> Yes, this is an issue in the current release v0.6.8. The [fix](https://github.com/guydavis/machinaris/commit/b6f644a4d6f183cb542795d9d08e5c0d8ab367f7) was made 15 days ago and has been available in the integration branch for a while now.
> 
> Please review the Staicoin channel in the [Machinaris Discord](https://discord.gg/mX4AtMTt87), where you will find that running this blockchain is currently not recommended to various defects present in their latest release.
