### ISSUE TITLE
a 0.75XCH Lesson, setting the xch_target_address

### ISSUE THREAD

**Issue by Isanderthul** [guydavis/machinaris#548]
**Describe the request**
It would be nice if the machinaris gui warned that the xch_target_address in the config is not recognized. Or provided a separate section in the /pools summary, a sample mockup below.

**Additional comments**
I won 2 blocks while pooling and was notified about the win. Checking the wallet I tried to find the transactions, which I could not. I then checked the config.yaml xch_target_address as described in 
https://blog.pool.space/how-to-find-your-0-25xch-after-winning-a-block-in-the-pool-fc61d0bee5c5

this address was not one I recognised, and I believe that the first time I installed chia on my virtual machine, it created a default wallet, which I must have deleted, when I imported the mnemonics of my laptop wallet that I had been using before getting my vm up and running, then when I moved over to machinaris and used that config.yaml the xch_target_address was moved across.
https://www.chiaexplorer.com/blockchain/address/xch1tlxkr0ex50atzuphd729pkrxqj476gkkfq5uz8f7092fy92zqmrqdtsasf
guess that is a .75 lesson, my pool only knew about the last two, and notified me that I had won those blocks. So when I had a look and investigated, thats when I realised that those wins were not showing in the wallet.
![Screenshot 2022-01-24 at 13 33 59](https://user-images.githubusercontent.com/3693197/150777048-3cb779a8-3664-4c2d-ac0d-e260e538a34b.png)

**Comment by guydavis** [comment]
Hi, sorry to hear that you had such a misconfiguration.  Good suggestion for a warning.  

FYI, your screenshot with two 'Chia' tabs at the top indicates a further misconfiguration with your Machinaris installation.  Please reset the [Machinaris databases](https://github.com/guydavis/machinaris/wiki/Troubleshooting#reset-machinaris-database).  If the duplicated 'Chia' tabs re-appear after 15 minutes, then the misconfiguration persists.

**Comment by guydavis** [comment]
Warning has now been added to the "Settings | Farming" page if the config.yaml file contains a `*_target_address` value which is not found in the configured hot/cold wallet addresses.  Thanks for the suggestion.

**Comment by guydavis** [comment]
Machinaris [version 0.8.0](https://github.com/guydavis/machinaris/releases/tag/0.8.0) has now been released with support for Chia 1.4.0.  Thanks!
