### ISSUE TITLE
add Free hd space to webinterface 

### ISSUE THREAD

**Issue by drdre1973** [guydavis/machinaris#55]
I would like to see added free plotting HD space so i know when to buy more hd's :)   
Maybe include When its full day ( due to constant plotting based on speed)

**Comment by guydavis** [comment]
Great suggestion!

**Comment by guydavis** [comment]
Available in test release. Shows current disk usage per plotting drive. Will be available soon in full release.

**Comment by guydavis** [comment]
Now available in v0.5.3+
