### ISSUE TITLE
Wallets page - Last reward column

### ISSUE THREAD

**Issue by cr8tor456** [guydavis/machinaris#552]
It would be great if the wallets page had a last rewards column so we can keep an eye on what's growing. 
It would also work as another indicator if a coin has not received a reward for an inordinate amount of time and needs looked into.

I think this would tie in well with the other enhancement request for the charts. Perhaps the wallet page could have a last reward column that when clicked on takes you to the charts page for that coin?

**Comment by guydavis** [comment]
Wallets page in upcoming release has a summary chart showing historical estimated value in your selected fiat currency of your entire farm: 
![image](https://user-images.githubusercontent.com/12936/173147967-bd8d56ce-c38c-4ed1-9301-b65c5b6f844d.png)

**Comment by guydavis** [comment]
Machinaris [version 0.8.0](https://github.com/guydavis/machinaris/releases/tag/0.8.0) has now been released with support for Chia 1.4.0.  Thanks!
