### ISSUE TITLE
Optional & configurable scheduled backup of the Chia (and forks) blockchain/wallet databases

### ISSUE THREAD

**Issue by guydavis** [guydavis/machinaris#555]
Very often, regular Chia users are encountering database corruption that breaks their farming on the full-node.   The only option seems to be a [database reset/resync](https://github.com/guydavis/machinaris/wiki/Troubleshooting#reset-chia-configwalletblockchain) which can take days, unless a database download is used.

While we wait for increased stability from the Chia Network development team in the underlying Chia application code, this enhancement would simplify the automated scheduling of backups.  Possibly implemented using [sqlite vacuum into](https://spacefarmers.io/wiki/guides/farming/backupdb).

**Comment by Isanderthul** [comment]
This is the way to backup the online database (node still running):
`sqlite3 /mnt/user/appdata/machinaris/mainnet/db/blockchain_v1_mainnet.sqlite "VACUUM main INTO /mnt/user/db/blockchain_v1_mainnet.sqlite.$(date -u +'%Y%m%d%H%M%S')"`

**Comment by Isanderthul** [comment]
https://github.com/Chia-Network/chia-blockchain/discussions/9900

**Comment by Isanderthul** [comment]
the spacefarmers writeup is very nice

**Comment by Yamanipanuchi** [comment]
So I attempted this and I get an error when I execute the command above (Yes I changed the paths to match my system).

**Comment by Yamanipanuchi** [comment]
I tried getting this function to work all weekend, No matter what I do I get a "Error: database is locked".

**Comment by Isanderthul** [comment]
general debugging things to try, see if you can list the tables in your database
```
╰─$ sqlite3 /Users/dev/.chia/mainnet/db/blockchain_v1_mainnet.sqlite                                                      1 ↵
SQLite version 3.32.3 2020-06-18 14:16:19
Enter ".help" for usage hints.
sqlite> .tables
block_records          full_blocks
coin_record            sub_epoch_segments_v3
sqlite> .databases
main: /Users/dev/.chia/mainnet/db/blockchain_v1_mainnet.sqlite
sqlite> .exit
```
the vacuum command works on an online database.
I notice you have back ticks `, you need normal ticks '  (unless this is just a formatting issue with github...)

**Comment by Isanderthul** [comment]
@Yamanipanuchi yup its the back ticks
```
╰─$ sqlite3 /Users/dev/.chia/mainnet/db/blockchain_v1_mainnet.sqlite "VACUUM main INTO `/tmp/backup.sqlite`"
zsh: no such file or directory: /tmp/backup.sqlite
Error: incomplete input
VS
╰─$ sqlite3 /Users/dev/.chia/mainnet/db/blockchain_v1_mainnet.sqlite "VACUUM main INTO '/tmp/backup.sqlite'"              
```

**Comment by guydavis** [comment]
Closing as with v2 database support, users are reporting fewer corruption issues.  As well, seems like this will be better handled by user's own backup solutions (vary user to user).
