### ISSUE TITLE
Challenges from Harvesters, delayed graph

### ISSUE THREAD

**Issue by Isanderthul** [guydavis/machinaris#556]
**Describe the bug**
The Challenges from Harvesters graph can take a while to populate, and look deceptively sparse for current values.

**To Reproduce**
Refresh graph at time X, save image, 
wait 2 minutes, 
refresh graph again, save image,
compare old graph values at X with new values at X

**Expected behavior**
It would be nice if the graph values for plotted points should be consistant, not eventually consistant. Maybe there should be a cutoff in the timeline (now-1minute)?

**System setup:**
Machinaris v0.6.9
ghcr.io/guydavis/machinaris:test

**Config**

</details>

**Additional context & screenshots**
![15-30 copy](https://user-images.githubusercontent.com/3693197/151558111-b260ca00-23d0-4ae8-818e-bf444a5bbd9a.png)

**Comment by Isanderthul** [comment]
maybe this is just how it has to be, which is ok if thats the case 🤷‍♂️

**Comment by guydavis** [comment]
Hi, this is a good point.  I'll delay display of the right-hand side of the chart by a couple of minutes in the next version.  Details on the [wiki](https://github.com/guydavis/machinaris/wiki/Chia#machinaris-page).  Thanks for the suggestion!

**Comment by guydavis** [comment]
Closing as [Machinaris version 0.6.9](https://github.com/guydavis/machinaris/releases/tag/0.6.9) has now been released.
