### ISSUE TITLE
Feature Request: Add plotting folder location column in plotting view

### ISSUE THREAD

**Issue by Jjjameson91** [guydavis/machinaris#56]
In the plotting view, add a column so the user can see what folder is associated with each plot being plotted. Especially useful if a plotting folder is running out of space and you need to kill a job.

**Comment by guydavis** [comment]
Good suggestion.  This is in the upcoming release v0.3.0:
![image](https://user-images.githubusercontent.com/12936/119706242-f1c96e00-be16-11eb-8723-e0da101a7c62.png)

Please keep in mind these directories are in-container, not host filesystem paths.  See the [FAQ ](https://github.com/guydavis/machinaris/wiki/FAQ#can-i-use-two-or-more-temporary-plotting-directories)for more.
