### ISSUE TITLE
Total Plots, how to find which harvester lost plots

### ISSUE THREAD

**Issue by Isanderthul** [guydavis/machinaris#577]
**Describe the request**
My UI reported that I had lost 554 plots in the last day. On investigating, it became clear that it is not immediately obvious which harvester lost the plots, as the Farming, Workers graph is only a current graph and does not have history. 

**Images**
<img width="278" alt="Screenshot 2022-02-14 at 16 41 19" src="https://user-images.githubusercontent.com/3693197/153886352-8e3b4b3d-2f69-4e6d-9ca3-c5e97e21db88.png">

maybe the graph for the space could be a daily graph
<img width="1448" alt="Screenshot 2022-02-14 at 16 50 41" src="https://user-images.githubusercontent.com/3693197/153887785-7a7d3eb9-2ceb-4d18-9421-35043c75dcdc.png">

**Comment by Isanderthul** [comment]
The problem was a disk IO issue on one of the harvesters (running unraid), which made the file system lock up so that no IO writes could occur. So the harvester in question no longer reported the space in the graph at all.
<img width="1566" alt="Screenshot 2022-02-14 at 17 03 04" src="https://user-images.githubusercontent.com/3693197/153888948-9b90b678-b1c7-469e-9c88-f4aea7926128.png">

**Comment by guydavis** [comment]
Good suggestion.  I'll look to add a warning on the Worker page too, when disk stats are not present.

**Comment by guydavis** [comment]
Some improvements will be made to the "Farming | Workers" page in the upcoming release.  Thanks for the feedback!

**Comment by guydavis** [comment]
Machinaris [version 0.8.0](https://github.com/guydavis/machinaris/releases/tag/0.8.0) has now been released with support for Chia 1.4.0.  Thanks!
