### ISSUE TITLE
error in the webui details for plotting process

### ISSUE THREAD

**Issue by cm86** [guydavis/machinaris#58]
the error exists when you click on the icon right from your plotting process...
pictures attached...
to get the error:
![error_plotting_details02](https://user-images.githubusercontent.com/14919688/119774340-5261b500-bec2-11eb-83c9-c06762484d50.PNG)
and here is the error
![error_plotting_details](https://user-images.githubusercontent.com/14919688/119774245-2b0ae800-bec2-11eb-8937-3ec8cfff52b9.PNG)

**Comment by guydavis** [comment]
Thanks for the feedback.  Would you be able to attach your `/mnt/user/appdata/machinaris/machinaris/logs/webui.log`, ideally right after triggering the error above again?  It would help reveal the cause.

**Comment by cm86** [comment]
ah forgotten...
excuse me...
attached you will find it...

[webui.log](https://github.com/guydavis/machinaris/files/6556217/webui.log)

**Comment by guydavis** [comment]
Ok, thanks.  It looks like there is a empty or nearly empty log file in /root/.chia/plotman/logs/.  I've added a guard in the code to not error if it finds such a nearly empty log but to continue on.  Available in

**Comment by cm86** [comment]
you were right, i found a logfile with no lines in it...
i deleted the file and the error was gone...

**Comment by guydavis** [comment]
Great.  I've improved the code to not faceplant in such a situation.  Thanks again!
