### ISSUE TITLE
[Bug]Can't add connections in Machinaris v0.3.0

### ISSUE THREAD

**Issue by Allram** [guydavis/machinaris#59]
See picture, can't add connections in the webui in v.0.3.0

![image](https://user-images.githubusercontent.com/5573149/119783288-5cd57c00-becd-11eb-9601-47af2eff2252.png)
[webui.log](https://github.com/guydavis/machinaris/files/6551980/webui.log)

**Comment by guydavis** [comment]
Thanks!  Great catch.  Just fixed in v0.3.0 test version.  Thanks for finding this before v0.3.0 is fully released.
