### ISSUE TITLE
More detailed reporting on plots

### ISSUE THREAD

**Issue by guydavis** [guydavis/machinaris#594]
![image](https://user-images.githubusercontent.com/12936/156486356-8dc67b63-1c03-4bc1-a00a-06133b02d4b5.png)

**Comment by Isanderthul** [comment]
this might tie in with https://github.com/guydavis/machinaris/issues/577, having a graph of the plots, or at least some way to tell why I mysteriously lost 566 plots.

**Comment by seertenedos** [comment]
I would also like to see more details but to do with harvesters. It would be great to see an up to date count of plots, harvester name and harvester ID if possible in a table. Trying to match the harvester to the one on the pool statistics page for my pool provider is hard and while the daying stats are good being able to see a live nbr of plots on a harvester would be very useful

**Comment by guydavis** [comment]
Some improvements will be made to the "Farming | Workers" page in the upcoming release.  Thanks for the feedback!

**Comment by guydavis** [comment]
Machinaris [version 0.8.0](https://github.com/guydavis/machinaris/releases/tag/0.8.0) has now been released with support for Chia 1.4.0.  Thanks!
