### ISSUE TITLE
Change "System Type" string to "Machinaris Mode" or just "Mode" in Worker Page

### ISSUE THREAD

**Issue by fabriziocacicia** [guydavis/machinaris#596]
**Describe the request**
As I was translating the Worker page I saw the string "System Type", and from the `message.po` file I was not able to understand what it was referring to. Open the actual page from my running machine I saw that it was referring to the 'fullnode' vs 'harvester' vs 'plotter' categorization.
But looking into the Wiki, this categorization is called 'Machinaris Mode'.

I was wondering if it is appropriate to continue to use the more generic "System Type" or switch to a more clear and consistent "Mode" or "Machinaris Mode". (or maybe it's more clear just for me, idk)

**Images**
<img width="510" alt="Screenshot 2022-03-03 at 14 34 01" src="https://user-images.githubusercontent.com/7525888/156575025-f39af1c5-680e-4b1c-bdcd-e804504c7343.png">

**Additional comments**

**Comment by guydavis** [comment]
Good suggestion.  Just committed this change to the `development` branch.  You should find only the 'Mode' string for translation there.  Here's what it looks like in English:

![image](https://user-images.githubusercontent.com/12936/156651821-54db5c8e-3af8-4aa9-8890-ea212dd6648b.png)

Thanks so much for your work on the Italian translation.  Really appreciated.  Let me know if you have any other questions!

**Comment by guydavis** [comment]
Closing as now generally available in the [Machinaris v0.7.0](https://github.com/guydavis/machinaris/releases/tag/0.7.0) release.  Thanks!
