### ISSUE TITLE
Feature Req. Plot Check

### ISSUE THREAD

**Issue by kdg1992** [guydavis/machinaris#6]
Add a Button that performs a plot check and show the result

**Comment by guydavis** [comment]
Great idea!  I'll definitely look to add this, but I'll need some type of long poll to show results in WebUI as it takes a minute or more for me at CLI, on my [10-year old box](https://guydavis.github.io/2021/01/30/unraid-server-setup/) running Unraid.

**Comment by guydavis** [comment]
Just added this to test version for v0.3.0.  Will hit mainline later this week, see "Check Plots" button:

![image](https://user-images.githubusercontent.com/12936/119573688-da847500-bd71-11eb-8b8e-db2647d783ea.png)

Pops open a log viewer to periodically poll the output (many minutes) of a `chia plots check` command.

![image](https://user-images.githubusercontent.com/12936/119573799-fab43400-bd71-11eb-9ca4-857f0de4a373.png)
