### ISSUE TITLE
[Maybe Issue] Maybe wrong word in 'api/commands/pools_cli.py:151' 

### ISSUE THREAD

**Issue by fabriziocacicia** [guydavis/machinaris#606]
### Description
In `api/commands/pools_cli.py:151` there is this phrase: 

> Successfully left pool, switching to self plotting. Please wait a few minutes or more to complete. DO NOT immediately re-submit your request. View the log for details.

#### **Argument**
Leaving a pool leads to self pooling. And regardless of being in a pool or not, you always plot by yourself for yourself.
So, I think that is not appropriate to use  _self plotting_ in the first phrase above.

### Proposed solution
Change the first phrase above to:
> Successfully left pool, switching to self pooling.

**Comment by guydavis** [comment]
Thanks.  Fixed in development stream.
