### ISSUE TITLE
Typo in web/translations/***/messages.po

### ISSUE THREAD

**Issue by fabriziocacicia** [guydavis/machinaris#632]
**Describe the bug**
Typo in https://github.com/guydavis/machinaris/blob/2aa35a32f645d447ebea1beacf2f5a49921c2339/web/translations/it_IT/LC_MESSAGES/messages.po#L116

It is also in all the other languages.

**Solution**
Should be 
```
msgid "Oops! No smartctl info found for device %(device)s on %(hostname)s."
```

It has to be fixed in all the other languages.

**Comment by guydavis** [comment]
This fix is now available in the [Machinaris v0.7.2 release](https://github.com/guydavis/machinaris/releases/tag/0.7.2) today. Thanks!
