### ISSUE TITLE
Missing localization for the start/stop archiving button

### ISSUE THREAD

**Issue by fabriziocacicia** [guydavis/machinaris#637]
**Describe the bug**
The top right action button to stop and start the archiving on the `/plotting/workers` page has not been localized. In particular, the archiving status part is not localized.

**Additional context & screenshots**
https://github.com/guydavis/machinaris/blob/95741d0cd78fee9605d7b47dcd08fa4f31b31f38/web/templates/plotting/workers.html#L106-L109

**Comment by guydavis** [comment]
Thanks! Fixed.

**Comment by guydavis** [comment]
This fix is now available in the [Machinaris v0.7.2 release](https://github.com/guydavis/machinaris/releases/tag/0.7.2) today. Thanks!
