### ISSUE TITLE
Drive monitoring needs enhancements

### ISSUE THREAD

**Issue by yurkessh** [guydavis/machinaris#642]
**Describe the request**
Drive monitoring doesn't seem to work properly with some setups.

**Additional comments**
I have a setup as follows.
1) A Supermicro server Acting as Full Node, Farmer and occasionally Plotter, carrying a mixed set of 24 drives including 8Tb SATA, 12Tb SATA and 12Tb SAS.
Backplane is controlled by an LSI SAS controller.

2) An HP DL380 Gen9 server carrying 12 SATA drives and acting as a harvester.
DL 380 backplane is controlled by the HP Smart Array P840 controller.

3) A Western Digital external storage appliance carrying 60 SAS drives and controlled by the DL 380 via a broadcom SAS controller.

So essentially the drives can be broke down into 3 groups.

Group 1 - Not shown in Machinaris at all.
Drives attached to the DL380 backplane. P840 controller wraps the drives as HP Logical Drives and thus those are not properly recognized by smartctl: one needs to add "-d" and specify the drive type, but even in that case we can't obtain temperature readings.
So probably this is a no-go.

Group 2 - Not shown in Machinaris at all.
Drives attached to the Supermicro backplane. These are accessible by smartctl from both the server itself and from docker container so I have no clue, why they are not shown.
I have attached a sample output of "smartctl -a" for both SATA and SAS drives.
[Seagate SATA Drive - Supermicro.txt](https://github.com/guydavis/machinaris/files/8418019/Seagate.SATA.Drive.-.Supermicro.txt)
[HGST SAS Drive - Supermicro.txt](https://github.com/guydavis/machinaris/files/8418021/HGST.SAS.Drive.-.Supermicro.txt)

Group 3 - Shown in Machinaris, but with no details.
Drives in the external storage. Probably SAS drives provide a different output that is not properly parsed by Machinaris.
I have attached a sample as well and the screenshot from Machinaris.
[WDC SAS Drive - Ext Storage.txt](https://github.com/guydavis/machinaris/files/8418020/WDC.SAS.Drive.-.Ext.Storage.txt)

Please let me know if any additional info is required.
Keen to help resolve this!
![Machinaris Screenshot](https://user-images.githubusercontent.com/85761756/161752840-7b6072b4-c21e-4a94-81c8-dcbf589fc872.jpg)
![Machinaris - Details](https://user-images.githubusercontent.com/85761756/161752849-9ed01e5a-e68c-434d-b77e-298d7433cca2.jpg)

**Comment by Isanderthul** [comment]
this joins with https://github.com/guydavis/machinaris/discussions/641

**Comment by guydavis** [comment]
Interesting! Please paste screenshots or snippets showing:

1. Full contents of your [docker-compose.yml](https://github.com/guydavis/machinaris/wiki/Drives) OR "Extra Parameters" field in the Machinaris docker configuration of Unraid.
2. `smartctl --scan` output from inside the container.
3. For each device listed by the scan, `smartctl -a /dev/DEVICE` 
4. For each device listed by the scan, `smartctl -a -d TYPE /dev/DEVICE`, where TYPE is listed above in the scan results.

This will help me understand your setup better.  Thanks!

**Comment by yurkessh** [comment]
Hi!

Output from the fullnode is attached. Apologies, I have a lot of drives so the output is rather long.
I will post the output from the Harvester in a separate message - it will be even larger since harvester carries 12 drives onboard, plus 60 drives in an external storage (attached via SAS).
Moreover the external storage has two SAS controllers for redundancy, thus insted of 60 drives, we get 120 mpath drives...

Anyway, let's start off with the simpler setup
[FullNode_smartctl-a-d_scsi.txt](https://github.com/guydavis/machinaris/files/8496647/FullNode_smartctl-a-d_scsi.txt)
[FullNode_docker-compose.yml.txt](https://github.com/guydavis/machinaris/files/8496652/FullNode_docker-compose.yml.txt)
[FullNode_smartctl--scan.txt](https://github.com/guydavis/machinaris/files/8496653/FullNode_smartctl--scan.txt)
[FullNode_smartctl-a.txt](https://github.com/guydavis/machinaris/files/8496655/FullNode_smartctl-a.txt)
.

**Comment by yurkessh** [comment]
Outputs for Harvester are attached.

I've also decided to provide you with the lsblk output so that you can probably better understand the set-up.
As you can see, the same drive can be seen, for example, both under sdas as mpatha1 and under sdda as mpatha1.
So each drive has a mapper - /dev/mapper/mpatha1, etc. 
Again. Physically there are 60 drives in the external storage, but since it has two controllers for redundancy, we have 2 paths to each drive.

Another interesting point which I noted is that both on the server itself and within the docker container smartctl --scan only shows 93 drives. So far I found out that it doesn't show drives sda..sdk, which are installed into the server front bays. Seems that the reason is that those are controlled by HP Smart Array, which I mentioned in the initial post. As such these drives require providing type and provide quite a useless output:

`[megaplotter@XXX~]$ sudo smartctl -a -d scsi /dev/sdb
smartctl 7.1 2020-04-05 r5049 [x86_64-linux-4.18.0-315.el8.x86_64] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               HP
Product:              LOGICAL VOLUME
Revision:             5.04
Compliance:           SPC-3
User Capacity:        12,000,105,070,592 bytes [12.0 TB]
Logical block size:   512 bytes
Physical block size:  4096 bytes
Logical Unit id:      0x600508b1001c54ca14fbfff0a203174e
Serial number:        PDNNF0ARH4520Q
Device type:          disk
Local Time is:        Fri Apr 15 20:17:34 2022 MSK
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Disabled or Not Supported

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK
Current Drive Temperature:     0 C
Drive Trip Temperature:        0 C

Error Counter logging not supported
[Harvester_smartctl-a-d_scsi.txt](https://github.com/guydavis/machinaris/files/8497219/Harvester_smartctl-a-d_scsi.txt)
[Harvester_smartctl-a.txt](https://github.com/guydavis/machinaris/files/8497220/Harvester_smartctl-a.txt)
[Harvester_smartctl--scan.txt](https://github.com/guydavis/machinaris/files/8497221/Harvester_smartctl--scan.txt)
[Harvester_Lsblk.txt](https://github.com/guydavis/machinaris/files/8497222/Harvester_Lsblk.txt)
[Harvester_docker-compose.yml.txt](https://github.com/guydavis/machinaris/files/8497223/Harvester_docker-compose.yml.txt)
`

**Comment by guydavis** [comment]
Thanks.  Latest `:develop` images of Machinaris, now support an override config file that will allow you to specify the `device_type` such as `sata`, `scsi`, etc that is passed to `smartctl -a -d DEVICE_TYPE /dev/sdX`.  Details can be found on [the wiki](https://github.com/guydavis/machinaris/wiki/Drives#override-command). Please let me know if this works in your case.  Thanks for the feedback.

**Comment by guydavis** [comment]
This fix is now available in the [Machinaris v0.7.2 release](https://github.com/guydavis/machinaris/releases/tag/0.7.2) today. Thanks!
