### ISSUE TITLE
Wallet balance 0

### ISSUE THREAD

**Issue by seertenedos** [guydavis/machinaris#663]
**Describe the bug**
On the wallet screen my Wallet Balance shows as 0 and my Cold Wallet Balance is correct.  I suspect it is because my balance is only 1599029 mojo but if you have less than say 0.001 XCH it should not show 0.  It shows further down on wallet details as
 -Total Balance:         1.599029e-06 xch (1599029 mojo)

**To Reproduce**
THis is not confirmed but this is what i suspect
Steps to reproduce the behavior, e.g.:
1. have a balance of less than 0.001 XCH

**Expected behavior**
DIsplay the wallet balance instead of 0.  This can be important as you need to have some mojo to change pool contracts and it was a little confusing when it said 0 at the top of the screen and 1599029 mojo further down the screen.  It would also be nice to have an option to see the balance in 0.0000001599029 as well as 1.599029e-06 xch (1599029 mojo).  If you need to add fees to something it is the long form that is needed and it can be confusing to convert mojo to long form.

**System setup:**
 - OS: Ubuntu
 - Docker version number (output of `docker info`)
 - Machinaris branch: develop 
 - Machinaris version number Machinaris 0.7.2

**Additional context & screenshots**
![image](https://user-images.githubusercontent.com/401009/167062175-569a0da6-5619-42c1-a1e3-40ec26237a3a.png)

**Comment by seertenedos** [comment]
wanted to say this looks good in the dev branch now

**Comment by guydavis** [comment]
This fix is now available in the [Machinaris v0.7.2 release](https://github.com/guydavis/machinaris/releases/tag/0.7.2) today. Thanks!
