### ISSUE TITLE
Updated via Unraid, farmer private key not found

### ISSUE THREAD

**Issue by sguy311** [guydavis/machinaris#67]
After updating the machinaris docker in unraid, my plots are showing the following message:
Warning! Chia is farming 0 plots, but Machinaris found 4 *.plot files on disk. See the FAQ.
When i run `chia plots check` , i see the following:
```WARNING  There are 4 plots with a farmer or pool public key that is not on this machine. The farmer private key must be in the keychain in order to farm them, use 'chia keys' to transfer keys. The pool public keys must be in the config.yaml```
I am quite new to this and I am sorry if the answer is obvious.

**Comment by guydavis** [comment]
Good question!  It seems that on start of the Machinaris container, your mnemonic.txt file with private key is not being added to the Chia service.  To ensure that it is, verify the existence of this file on your Unraid Host OS: `/mnt/user/appdata/machinaris/mnemonic.txt`.  This file should contain your mnemonic seed phrase, words separated by spaces, on a single line, ready for [import](https://github.com/guydavis/machinaris/wiki/Keys).   

Once you're sure the file is in place, restart the Machinaris container and take a look at the Machinaris "Logs" view from Unraid's Docker tab.  You should see output like `key at path: {/root/.chia/mnemonic.txt}`, indicating the key was imported on launch.  Then view the Wallet page of Machinaris WebUI to verify the public view of your key is present.

If this doesn't work, please take a look at the [Machinaris logs on disk](https://github.com/guydavis/machinaris/wiki/Troubleshooting#nothing-works--where-are-the-logs) to see what happened.  Hope this helps.

**Comment by guydavis** [comment]
Closing as no further comments received.
