### ISSUE TITLE
Feature req: Add 'Cleanup' button to clean up failed plots

### ISSUE THREAD

**Issue by Allram** [guydavis/machinaris#7]
Add a button that cleans/empties drives/folders used for plotting.
This is especially useful when you update docker or restart it and need to restart plots that is then marked as failed and is just taking up space on the HDD's.

**Comment by guydavis** [comment]
Hi!  I just released v0.2 which adds a 'Kill' button to the WebUI for plots.  It invokes Plotman's kill function which actually does clean-up all associated temp files for the plot being killed.  Sound good?

**Comment by guydavis** [comment]
Closing this as 'Kill' button to clean up a plots temporary files is sufficient for now.

**Comment by guydavis** [comment]
Re-opening as there is case where a restart of container without Kill of plots first leaves temp files behind.  Perhaps this check could be tied into the 'Plot On!' button to check/confirm/delete before starting a plotting run again.

**Comment by guydavis** [comment]
I've added a cleanup of any [stale *.tmp files](https://github.com/guydavis/machinaris/wiki/Plotman#temporary-storage) in temporary storage locations when starting Plotman in Machinaris AND no current plotting jobs are running or stopped.  

Will be available in Machinaris test version later today, then full release next week or so.  Thanks!

**Comment by efnats** [comment]
Stale *.tmp files don't get cleaned up in tmp2 directory which results in the plotter not starting.
