### ISSUE TITLE
RuntimeError: std::exception

### ISSUE THREAD

**Issue by breiti78** [guydavis/machinaris#70]
When trying to use the plotting functionality a I get a "RuntimeError: std::exception"
I've testes if the drive are mounted correctly to the container and if a I read/write access as well for the /plotting and for the /plots directory this is working fine.
We I try to manually create a plot using the chia commandline I get the same error.
I'm running the :latest version of machinaris freshly installed today.

**Comment by guydavis** [comment]
Welcome! Sorry to hear you're having an issue.  Please let us know your OS platform, and attach the logs from the following locations in your `.machinaris` folder:

- plotman/logs/
- machinaris/logs/
- mainnet/log/

Also, the output of the Docker launch would be useful.  In Unraid, this the 'Logs' view for the Machinaris container.  If, this is a `docker run`, try launching without the `-d` flag and watch the terminal/console for output.

After submitting these logs and given this is a fresh install, I would probably recommend that you, first ensure your mnemonic.txt is safely saved/recorded.  Then stop the running container, delete entire `.machinaris` folder, and launch again.  Follow the [post-launch configuration steps](https://github.com/guydavis/machinaris/wiki/Docker#post-install-configuration).  Hopefully this resolves your issue.

**Comment by breiti78** [comment]
Thank you for the fast reply.
I found the root cause for the issue which was due to my underlying setup. I was running the docker container in a Ubuntu VM in Proxmox. Looking into the error log showed the issue with bitfield. So I've changed my setup now and remove the proxmox layer.
This issue can be closed. Thank you
