### ISSUE TITLE
Paho MQTT module was not found

### ISSUE THREAD

**Issue by scorpio862** [guydavis/machinaris#71]
I'm trying to use MQTT Notifications from Chia Dog but I get this error messages:

[   ERROR] --- Message delivery failed because the Paho MQTT module was not found. Please refer to INTEGRATIONS.md for help on resolving this issue.  (mqtt_notifier.py:109)
[   ERROR] --- Failed to send events over mqtt (notify_manager.py:64)

I've installed the Paho MQTT package as it says in INTEGRATIONS.md but it still doesn't work

**Comment by guydavis** [comment]
Good catch!  Based on the Chiadog [integrations page](https://github.com/martomi/chiadog/blob/main/INTEGRATIONS.mdhttps://github.com/martomi/chiadog/blob/main/INTEGRATIONS.md), it looks like I need to include: `/chia-blockchain/venv/bin/pip3 install paho-mqtt`

I'll get this into the `:test` release for now and target release in upcoming v0.3.1 later this week.  In the meantime, as a workaround, please try executing above command from an in-container shell.  It should last as long as the container is running.  Thanks again.
