### ISSUE TITLE
Plots stuck in phase 3 for days

### ISSUE THREAD

**Issue by AliMickey** [guydavis/machinaris#77]
Hello,

plotman started two plot jobs before i stopped it to let them finish (for testing/learning). 

Both of them are in phase 3 and seem to be stuck. 

![image](https://user-images.githubusercontent.com/60691199/120566025-a71ca700-c451-11eb-8119-2dd2ec7d258b.png)

![image](https://user-images.githubusercontent.com/60691199/120566018-a08e2f80-c451-11eb-9382-9eb20d5dec69.png)

Node is fully synced if that makes a difference. Both the tmp and final dest is on a dedicated harddrive. It has sufficient space.
![image](https://user-images.githubusercontent.com/60691199/120566095-ddf2bd00-c451-11eb-852c-d1d3e773e24c.png)

Summary: 
![image](https://user-images.githubusercontent.com/60691199/120566119-eb0fac00-c451-11eb-8282-3e1fc8b4708f.png)

The initial plot is one i made using the official gui before migrating to this. 
The temp folder is full of .tmp files.

**Comment by AliMickey** [comment]
BTW my system is constantly on around 50% cpu usage with no disk usage.

![image](https://user-images.githubusercontent.com/60691199/120566265-3924af80-c452-11eb-8fa9-188efcfa7a6a.png)

**Comment by guydavis** [comment]
Hello! Yes, that doesn't seem seem correct.  Please take a look at some in-container info via `docker exec -it machinaris bash`:
```
df -hT
ps auxw | grep "plots create"
```
Is the problem repeatable for your setup?  I would recommend killing the plots via the Plotting page and restarting the Machinaris container after clearing out the temp files.

As this issue seems to be Plotman-related, you may want to open an issue in their [Github issues].(https://github.com/ericaltendorf/plotman/issues)

**Comment by AliMickey** [comment]
![image](https://user-images.githubusercontent.com/60691199/120599018-4fe6f880-c48a-11eb-805d-9d57840f89fd.png)


Won't i lose the tmp files? I was hoping to recover the queue somehow and finish them off. Otherwise i will probably just use the official cli/gui as i do not want to be uselessly stressing out my HDD.

**Comment by guydavis** [comment]
Yes, if you kill the plots then you would need to restart from zero, but days is far too long.  Please share the complete `docker run` command you are using.  I am interested to see your volume mappings to `/plots` and `/plotting`.

**Comment by AliMickey** [comment]
![image](https://user-images.githubusercontent.com/60691199/120760166-27790000-c557-11eb-903b-f64507aceb61.png)

**Comment by guydavis** [comment]
Hi, that docker compose looks good from what I can tell.  Sorry for the trouble you're encountering. 

FYI, there is a [new release today](https://github.com/guydavis/machinaris/releases/tag/0.3.1), so it may be worth upgrading and trying again to see if this recurs.  

Please start with a single plot at a time (global_max_jobs=1 in Settings | Plotting).  If that works, then increase the Plotting settings to get more jobs running in parallel.

**Comment by AliMickey** [comment]
Updated and changed the config now.

Started a new plot, if this does not complete then unfortunately ill have to go back to the official gui. 

I'll be happy to test and provide logs/support though to fix this.

**Comment by AliMickey** [comment]
Sadly its been stuck here for a while again.

![image](https://user-images.githubusercontent.com/60691199/120890382-afd5ce80-c645-11eb-871f-345b98e86f8e.png)

![image](https://user-images.githubusercontent.com/60691199/120890388-b5331900-c645-11eb-9a47-98c77db67891.png)

**Comment by AliMickey** [comment]
I think it may be a bad ram stick, dont know how my initial plot went through but now nothing else is finishing. I'll close this for now and try this tool again down the line when i replace the stick.

Thanks
