### ISSUE TITLE
Get Machinaris listed in the TrueNAS application repository

### ISSUE THREAD

**Issue by guydavis** [guydavis/machinaris#78]
Thanks to Game_Wylder on Discord for the tip.  Looks like [TrueNAS ](https://www.truenas.com/truenas-scale/) requires a [helm chart](https://github.com/truecharts/apps) defining the Docker deployment.  Anyone interested in helping out here?

**Comment by kmoore134** [comment]
This has been done, Machinaris is now available in the "Official" TrueNAS SCALE apps repo, thanks to [iXsystems](https://www.ixsystems.com) and the [TruePool.io](https://truepool.io) team :)

https://github.com/truenas/charts/pull/109

**Comment by guydavis** [comment]
Big thanks to @kmoore134 for all this work, including some [great documentation](https://github.com/guydavis/machinaris/wiki/TrueNAS).
