### ISSUE TITLE
Plotter Graph Wrong Name

### ISSUE THREAD

**Issue by inabon** [guydavis/machinaris#782]
**Describe the bug**
Plotter Graph Has Wrong Name

**To Reproduce**

Steps to reproduce the behavior, e.g.:
click on plotting link at controller WGUI
controller name on plotter times graphs

**Expected behavior**
controller and full node name mephistopheles
plotter on remote computer Satanas
Satanas should be the one shown on plotting time graphs

**System setup:**
Ubuntu controller
Unraid plotter

**Config**
<details><summary>full configuration</summary>

```
# paste your Docker run or Docker compose here
```

</details>

**Additional context & screenshots**
![image](https://user-images.githubusercontent.com/42424297/194799398-2dc05090-a096-45a4-9d95-27992707ceb9.png)

**Comment by guydavis** [comment]
Hi, thanks for the report.  To better understand the issue, please share:

1. A full window screenshot of your Workers page, as well as screenshots for each Worker (click into them from link in table on Workers page).
2. The full docker configuration for your Plotter system from the Unraid UI | Docker tab, edit 'Machinaris' container.  Given the size of this configuration window, it may mean a few screenshots, scrolled down to get it all.

Thanks.

**Comment by inabon** [comment]
found the issue. my mistake sorry bout that.
