### ISSUE TITLE
option to select role

### ISSUE THREAD

**Issue by technickal1** [guydavis/machinaris#79]
it would be awesome to have a start interface with toggles for each
[] harvester
[] plotter
[] farmer
[] full node

**Comment by rangulicon** [comment]
This would be awesome if possible, but probably more feasible to just re-deploy the image as a container with your preferred roles.

**Comment by guydavis** [comment]
Now available in test image: `ghcr.io/guydavis/machinaris:test`, the [mode environment variable](https://github.com/guydavis/machinaris/wiki/Docker), passed to Docker, has been extended to allow two more modes: `harvester+plotter` and `farmer+plotter`, allowing dual-use for those cases.

**Comment by guydavis** [comment]
Closing as v0.4.0 has been released.  Thanks for the contribution!
