### ISSUE TITLE
Update icon on running services from pause to stop

### ISSUE THREAD

**Issue by zorner** [guydavis/machinaris#809]
**Describe the request**
In Plotting when stopping the plotting service or archiving service the icon is a pause icon, 2 rectangles. It should be a single square for stop.

**Images**
![image](https://user-images.githubusercontent.com/5413793/201518485-ef85f26e-1429-4baf-9708-d45d9b9aa5b8.png)

**Comment by zorner** [comment]
New stop Icon looks great!

**Comment by guydavis** [comment]
Now available in version of [0.8.6](https://github.com/guydavis/machinaris/releases/tag/v0.8.6) of Machinaris. Thanks!
