### ISSUE TITLE
Setting multiple plots folders , plots don't show in farming view.

### ISSUE THREAD

**Issue by sparklyballs** [guydavis/machinaris#81]
For my setup I need to set 3 different locations for the stored plots, so i've edited the config yaml file to reflect this. the summary shows the correct number of plots for the combined total of the 3 locations, however if I go to the farming view it only shows plots in /plots
Ideally i'd like to map /plots/1 /plots/2 /plots/3 container locations to my 3 host paths but if i do this no plots show in the farming view and again the summary view is correct.

**Comment by guydavis** [comment]
Hi again!  This is definitely supported.  Be sure to pass all your plots dirs in the colon-separated `plots_dir` env var on container startup.  Please see this [FAQ](https://github.com/guydavis/machinaris/wiki/FAQ#can-i-use-two-or-more-final-destination-directories-to-hold-my-plots).

**Comment by sparklyballs** [comment]
Damn, lol. 

Guess who didn't RTFM !!!!

**Comment by sparklyballs** [comment]
oh, and hi back.
working now... thanks.
