### ISSUE TITLE
Get rid of redundant start/stop button in pop-up/modal

### ISSUE THREAD

**Issue by zorner** [guydavis/machinaris#810]
**Describe the request**
The user has already clicked the worker and the start/stop menu that comes up. Having to click start/stop again in the pop-up/modal is redundant. There is a cancel button, so if the user hit this in error, they can simple cancel. The pop-up/modal should automatically try to start or stop the service.

**Images**
![image](https://user-images.githubusercontent.com/5413793/201518787-03c5273f-817a-40d6-b32a-d09e043f1d02.png)

![image](https://user-images.githubusercontent.com/5413793/201518985-fdd4e8c9-48a1-42c1-8619-daa9ccd7bd54.png)

**Comment by guydavis** [comment]
Sorry, we'll have to agree to disargee on this one.  As an action which doesn't happen very often, I want it to be 100% clear to users what will be happening.
