### ISSUE TITLE
Archive.log needs timestamps and archiving dir is making empty files

### ISSUE THREAD

**Issue by zorner** [guydavis/machinaris#812]
**Describe the request**

Archive.log needs timestamps and archiving dir is making empty files. And as with [Remove looped log entries from plotman.log](https://github.com/guydavis/machinaris/issues/811), "Sleeping 20 s until next iteration..." is redundant and cluttering up the log.

**archive.log:**
```
Sleeping 20 s until next iteration...
Sleeping 20 s until next iteration...
Sleeping 20 s until next iteration...
Sleeping 20 s until next iteration...
Sleeping 20 s until next iteration...
Starting archive: /tmp/plotman-pid_10808-u84oax24/plotman-transfer-scriptjxyu71_p ; logging to /root/.local/share/plotman/transfers/2022-11-06T05_16_10.556676-05_00.transfer.log
Sleeping 20 s until next iteration...
Sleeping 20 s until next iteration...
Sleeping 20 s until next iteration...
Sleeping 20 s until next iteration...
```

**Images**
![image](https://user-images.githubusercontent.com/5413793/201521513-23a2f626-0ef5-4207-b71b-65fd3e49070a.png)

**Comment by zorner** [comment]
Odd on a different plotter that was doing a remote transfer, archiving did have info in the logs. The one shown above was for a local transfer, that did move successfully.

**From the remote transfer:**

```
Launching transfer activity
rsync error: syntax or usage error (code 1) at clientserver.c(1223) [Receiver=3.2.3]
rsync: did not see server greeting
rsync error: error starting client-server protocol (code 5) at main.c(1675) [sender=3.1.3]
```

I do not think I have rsyncd running on the harvester or the port is blocked.

**Comment by zorner** [comment]
Found the issue with the log files in archiving dir. I am using custom transfer_script. The output from the transfer_script is what is put in the log files in the archiving dir. My local transfer_script had no echo statements, thus it did its job and exited with no output.

**Comment by guydavis** [comment]
Great. Glad you sorted it out.
