### ISSUE TITLE
Restful support

### ISSUE THREAD

**Issue by anschein** [guydavis/machinaris#820]
For now I can see there is so many ways to get notification from chiadog,but I'm using home assistant and hope to get wallet balance from restful or something like this,Is there any function already here or can we have one?
Thanks for amazing work of this project!!

**Comment by guydavis** [comment]
Hi, thanks for your interest.  Did you take a look at the REST API mentioned on the [project page](https://github.com/guydavis/machinaris#rest-api)?  There is room for improvement of course, and [contributions are welcomed](https://github.com/guydavis/machinaris/wiki/Contributing).

![image](https://user-images.githubusercontent.com/12936/207646193-8d4ffd1f-1ad1-4e40-a067-15320f72e30a.png)

![image](https://user-images.githubusercontent.com/12936/207646686-004afec6-5d35-49c2-9747-bef796a13c3d.png)

**Comment by anschein** [comment]
Sorry,I have miss this part,I'll try into my HA.
Thanks!

**Comment by guydavis** [comment]
Great, closing then.
