### ISSUE TITLE
Daily schedule to start/stop Plotman plotting loop - during periods of cheap electricity

### ISSUE THREAD

**Issue by guydavis** [guydavis/machinaris#821]
![image](https://user-images.githubusercontent.com/12936/208309657-deb2daaf-4ceb-43ec-9a12-8d5c2d318c3c.png)

**Comment by guydavis** [comment]
![image](https://user-images.githubusercontent.com/12936/209058767-56afea5e-e8ce-4a50-bd71-ad7b1f894b45.png)

**Comment by Tindog33** [comment]
Would it also be possible with that to potentially limit how many cores go at different times during the day like... during the day run at 50% of what I have set you up to do. At night run at 100% of what I have told you to do. That way for those that use their computer during the day it can kinda run in the background, but at night it can run full. There is actually a software I have used that does this, it does math/science research at universities, it's called BOINC (It's an Unraid app too) and it works great, I would love if machinaris has some similar features, if possible. Also it causes a thing similar to "plotting" to start if your computer goes idle.

These are what the settings look like if that can give you some ideas.
![Boinc1](https://user-images.githubusercontent.com/46406955/209790187-3f7acfc0-0223-40cc-94b7-a48ac22e9cfe.png)
![Boinc2](https://user-images.githubusercontent.com/46406955/209790190-8cd955c7-3a11-4b43-8482-73785485d6b5.png)
![Boinc3](https://user-images.githubusercontent.com/46406955/209790192-3c5d49c3-1da0-4fa1-9fbe-5ddd0c8ad16c.png)
![Boinc4](https://user-images.githubusercontent.com/46406955/209790195-e175c434-6a6b-40b4-b7e0-a95f026ad36a.png)

**Comment by guydavis** [comment]
I have a cron based approach for this available now in the `machinaris:develop` image, click the Calendar icon on the Setting | Plotting page, after selecting your worker machine and blockchain (Chia, Chives, MMX):

![Screenshot from 2023-02-10 21-22-37](https://user-images.githubusercontent.com/12936/218239700-bb73ed70-f333-4a8f-87e7-e3d5ccaef638.png)

Allows multiple start/stop schedules, based on cron-criteria.  All feedback is appreciated.

**Comment by guydavis** [comment]
Available now in the Machinaris [v0.8.7 release](https://github.com/guydavis/machinaris/releases/tag/0.8.7).
