### ISSUE TITLE
[Request] Use netcat over rsync

### ISSUE THREAD

**Issue by authrequest** [guydavis/machinaris#84]
Chia Plot Manager utilizes netcat over rsync due to the speed at which it transfers plots over the network faster.

Implementation Below: (I know main script is python but it can be changed for this)
https://github.com/rjsears/chia_plot_manager/blob/main/chiaplot/send_plot.sh
line 134: https://github.com/rjsears/chia_plot_manager/blob/main/chiaplot/plot_manager.py

**Comment by guydavis** [comment]
Interesting suggestion.  Machinaris bundles the Plotman plot manager and thus uses Plotman's archiving feature based on rsync.  Please open this request in [their Github issues](https://github.com/ericaltendorf/plotman/issues).
