### ISSUE TITLE
Enable client-side caching of static files

### ISSUE THREAD

**Issue by qoole** [guydavis/machinaris#841]
Add: 

`SEND_FILE_MAX_AGE_DEFAULT = 86400` 
to 
`/machinaris/web/default_settings.py`

This tells flask to add a suitable `Cache-Control` header to all static files. Improving responsiveness of the UI by not having to fetch all .css and .js files every page load

**Comment by guydavis** [comment]
Very good suggestion! Thanks for bringing this to my attention.  Please keep the excellent contributions coming.

**Comment by guydavis** [comment]
Available now in the Machinaris [v0.8.7 release](https://github.com/guydavis/machinaris/releases/tag/0.8.7).
