### ISSUE TITLE
Duplicate Plots not disappear

### ISSUE THREAD

**Issue by Baatezu** [guydavis/machinaris#847]
Duplicate Plots not disappear after restart docker. Also if update (but im not remember not sure its not helping)

**To Reproduce**

use same plots in different folder than delete one.

**Expected behavior**
should disappear after time or reboot or etc.

**System setup:**
Linux
Machinaris 0.8.6

**Comment by guydavis** [comment]
Thanks for the report.  I am still investigating why the warnings are not be removed shortly (hour or so) after the underlying duplication is cleared.  In the meantime, I've added a "Clear All" button in the [upcoming version of Machinaris](https://github.com/guydavis/machinaris/wiki/Releases) to quickly remove all Warnings on the Farming page.  Only if a warning comes back is it still being reported by Chia services layer and not stale in Machinaris.  

![image](https://user-images.githubusercontent.com/12936/215548134-6d06ddb7-8600-4f95-bdf7-d7b92332ae3f.png)
