### ISSUE TITLE
AppArmor profile for Chia Node

### ISSUE THREAD

**Issue by carlosvsilva** [guydavis/machinaris#85]
Hi. I would really enjoy running the Chia fullnode with MAC security like Ubuntu AppArmor, just in case since there's an open port to the Internet. Is there anyone interested in creating an AppArmor profile to run the fullnode inside the container? I might be able to help. Thanks :)

**Comment by guydavis** [comment]
That would be great.  Any help you can provide would be really appreciated!

**Comment by guydavis** [comment]
Hi, with the recent availability of the [Machinaris launch wizard](https://www.machinaris.app/) (simple form to generate the Docker run/compose), I wonder if anyone has tried this with the `docker-default` [app-armor profile](https://docs.docker.com/engine/security/apparmor/#understand-the-policies).  Perhaps this already works?

**Comment by guydavis** [comment]
Hi, v0.6.0 now is multi-container to allow for running multiple blockchain forks such as flax, n-chain, chives, hddcoin, etc.  All details at https://www.machinaris.app/ where one can generate a docker-compose.yml.
