### ISSUE TITLE
Version in UI dont match

### ISSUE THREAD

**Issue by SauravKumal** [guydavis/machinaris#86]
I updated to latest chia version 1.1.7 but the web ui shows 1.1.6. Logged in to docker bash to check and it is 1.1.7. So maybe UI didn't update?

**Comment by guydavis** [comment]
Yes, I've had to workaround some interesting upstream versioning in the Chia binaries when displaying on the Machinaris webui.  I've just released a patch update to Machinaris v0.3.2 which now includes above Chia version.  Please give it a try when you next upgrade, when taking a break from plotting.

**Comment by SauravKumal** [comment]
Okay will give it a try.
