### ISSUE TITLE
Ability to run a timelord as well during container launch.

### ISSUE THREAD

**Issue by guydavis** [guydavis/machinaris#868]
![image](https://user-images.githubusercontent.com/12936/221911613-3689bb57-6a7e-4c48-95c7-691e4ce4ccaa.png)

**Comment by ApfelBirneKreis** [comment]
Hello Guy i did manage to built a timelord by itself with adding those variables. Everything we need now is the command "stai start timelord" when starting the container and setting the mode to "fullnode,timelord"
![image](https://user-images.githubusercontent.com/84158946/222251183-9f001f47-1300-4bf3-987f-ed562b4df44b.png)

**Comment by ApfelBirneKreis** [comment]
unraid in this case.

**Comment by ApfelBirneKreis** [comment]
Launcher Error:
``
/machinaris/scripts/forks/staicoin_launch.sh: line 66: conditional binary operator expected
/machinaris/scripts/forks/staicoin_launch.sh: line 66: syntax error near `~='
/machinaris/scripts/forks/staicoin_launch.sh: line 66: `if [[ ${mode} ~= ^fullnode.* ]]; then'
Welcome to Machinaris v0.8.8!
staicoin - fullnode,timelord on x86_64
Configuring Staicoin...
Adding key at path: /root/.chia/mnemonic.txt
Adding plot directories at:  /plots1, /plots2, /plots3, /plots4, /plots5, /plots6, /plots7
``

**Comment by guydavis** [comment]
Thanks for testing so fast, already fixed in next commit.

![image](https://user-images.githubusercontent.com/12936/222270544-f96edfba-b2db-4bf8-80fd-9e517775c2a6.png)

Let me know how it goes. Thanks.

**Comment by ApfelBirneKreis** [comment]
nice! will do :)

**Comment by ApfelBirneKreis** [comment]
awesome, working!

**Comment by guydavis** [comment]
Actually, there was another typo I had.  Just fixed that one and am testing in Chia image now too.  Will roll out to others shortly.

![image](https://user-images.githubusercontent.com/12936/222273665-c629b3a4-4a8a-4c23-ab93-29fbc1e910e4.png)

**Comment by ApfelBirneKreis** [comment]
nice work! will try again shortly

**Comment by Axadiw** [comment]
Hey (probably) silly question - What are the advantages of running local timelord of the network. Besides of supporting the network (of course) :)

Would it be beneficial for speeding up / stabilizing network synchronization of the rest of local full node modules?

**Comment by guydavis** [comment]
> Hey (probably) silly question - What are the advantages of running local timelord of the network. Besides of supporting the network (of course) :)
> 
> Would it be beneficial for speeding up / stabilizing network synchronization of the rest of local full node modules?

I think you're correct the [main benefit is to the network itself](https://github.com/Chia-Network/chia-blockchain/wiki/Timelords).

**Comment by gibblinhimer** [comment]
It depends what type of timelord you are running.

A regular timelord generates\verifies proofs and moves the block chain forward. Only one is needed and the fastest one on the network does the work. the others are for redundancy.

A bluebird timelord takes those hefty proofs and then compresses them to keep the block chain lean and mean.
For this type, the more the merrier, as much of the blockchain contains uncompressed proofs so having as many as possible out there would streamline the blockchain and make syncing much faster for all. Not to mention reduce the size of the block chain DB.

**Comment by guydavis** [comment]
Now available in [Machinaris v0.8.8](https://github.com/guydavis/machinaris/releases/tag/0.8.8).  Thanks for this suggestion!
