### ISSUE TITLE
Plotman Archive must be manually started from container CLI

### ISSUE THREAD

**Issue by guydavis** [guydavis/machinaris#88]
When plotman.yaml has archive settings enabled, the 'Plot On!' and 'Stop Plotman' buttons should also start/stop a separate `plotman archive` loop, not just the main `plotman plot` loop.  Seems this archive behavior is a bolt-on requiring a separate process.

Machinaris does [support archiving via Plotman](https://github.com/guydavis/machinaris/wiki/Plotman#archiving) over rsync. I am running this myself, with two Windows plotters rsyncing over plots to an Unraid server. That said, this Plotman archiving support could be improved in Machinaris.   This issue will encompass those improvements.

**Comment by iamchriswick** [comment]
https://github.com/ericaltendorf/plotman/wiki/Archiving

**Comment by iamchriswick** [comment]
Any suggestions on how to solve archiving when network drive is on same host system as Machinaris? `ssh user@localhost` does not seem to work from docker to host machine and vice versa.

**Comment by guydavis** [comment]
Hi!  So, Plotman just re-worked [Archiving](https://github.com/ericaltendorf/plotman/wiki/Archiving) in their latest version: 0.4.1.  They seem to have improved "local" behavior.  There is a preview of Machinaris in test right now that includes this Plotman 0.4.1 version.  

This test Machinaris also includes some large changes to support [managing multiple Machinaris workers on your LAN](https://github.com/guydavis/machinaris/wiki/Workers).  If you're up to test it out, please give it a shot and provide your feedback here.  Thanks!

**Comment by guydavis** [comment]
So, with latest release of Plotman, there is a new [plotman.yaml configuration](https://github.com/ericaltendorf/plotman/wiki/Archiving#remote-rsyncd-archiving) with `archiving` as top-level.  Once I changed my old config to match the new Plotman version expectations, I was able to use the new per-worker menu to start/stop archiving:

![image](https://user-images.githubusercontent.com/12936/122656469-19f77480-d118-11eb-89f0-4a3c25a9f31d.png)

**Comment by BasvanH** [comment]
@guydavis, as #88 is resolved, you can remove the comment about it from the [wiki](https://github.com/guydavis/machinaris/wiki/Plotman#archiving).
