### ISSUE TITLE
setup.html convert the mnemonic seed to lowercase before processing it

### ISSUE THREAD

**Issue by Baatezu** [guydavis/machinaris#895]
**Describe the request**

In some cases user can start mnemonic from capital letter or all words for capital letters and its save same but chia can't start because its case-sensitive. To prevent this better to change little bit code. are better user-friendly :)

**Additional comments**
[Pastebin Code](https://pastebin.com/WJF8S3mf)

**Comment by guydavis** [comment]
Now available in the [latest Machinaris release](https://github.com/guydavis/machinaris/releases/tag/1.8.0).
