### ISSUE TITLE
Add criteria for selecting plots to delete non-compressed plots

### ISSUE THREAD

**Issue by toto99303** [guydavis/machinaris#897]
**Describe the request**
As compressed plots are reality now and soon we will be able to farm them natively we need to replot and replace all old plots over time. Please add criteria for selecting plots to delete non-compressed plots automatically on small portions.

**Comment by guydavis** [comment]
Sure, I'll take a look.  Please share an example plot filename from a Bladebit-created "compressed" plot.  I'm looking to see if CNI chose to add to the filename the same way that Max did for Gigahorse.  Thanks.

**Comment by toto99303** [comment]
Sure, here's an example of c09 compressed plot:

plot-k32-c09-2023-03-24-15-09-c3dd5be80d633860e0b03609132894d02c6c4ece8e017f9b5e10b27a9f96e9d1.plot

**Comment by guydavis** [comment]
Thanks, I've just committed more code to support Bladebit's different (zero-padded) naming standard for compressed plots.  Please try out the most recent `machinaris:develop` image and let me know what you find when searching `replot` in the controller's server log. Thanks again.

**Comment by guydavis** [comment]
Now available in the [latest Machinaris release](https://github.com/guydavis/machinaris/releases/tag/1.8.0).
