### ISSUE TITLE
Feature req: Discord notification

### ISSUE THREAD

**Issue by Allram** [guydavis/machinaris#9]
Add a possibility in Alerts to send notifications via Webhook to Discord.

T.ex:
Plots startet
Plots finished (time to make etc.)
Coins farmed
Optional hourly status update (or adjustable time updates)

**Comment by Aerya** [comment]
You could just use this repo for a bot: https://github.com/joaquimguimaraes/chiabot
I think he might not add more and more useless features to a simple CHIA client-farmer Docker.

**Comment by guydavis** [comment]
Hey @Allram!  I've integrated [Chiadog ](https://github.com/martomi/chiadog)with Machinaris and users have confirmed discord notifications are working.  Currently on the test branch, will hit release mainline later this week.
