### ISSUE TITLE
Improvements to Wallets page (various)

### ISSUE THREAD

**Issue by Malixk-pc** [guydavis/machinaris#90]
Though it might be nice to have an transaction page, where you can easly see done transactions, do deposits and/or withdrawal from the wallet. Maybe at the wallet page? Am sorry I cant code, so i cant help out with that.
Some lines and ideas
-chia wallet get_adress
--for makeing deposits onto the wallet. Maybe at the top, with an copy button. Dont know about QR, dont like em.
-chia wallet send -i -a -m -t
-- Sends coins. dont know, just match chia ui?
-chia wallet get_transactions
--shows all transactions. Mayb have this at the bottom on the page
-

**Comment by guydavis** [comment]
Some points suggested from Discord.  

1. When more than one key has been loaded, we need a way to switch between the active wallet.  
2. Would be nice to stop/start the current wallet syncing for a fork, perhaps on a scheduled/rotating basis to decrease memory usage by all forks at same time.
3. _"i just changed to solo plotting and my chia has multiple wallet ids. i think it would be a great feature to add a bubble select to pick the wallet id to change pools or change to solo. whatever wallet id is selected would then be automatically placed in the chia plotnft -i walletid command.  i think it would be great to if there was a way to implement starting a new wallet id from gui as well."_

**Comment by guydavis** [comment]
Upcoming release includes an Improved read-only Wallet display.  As discussed, wallet actions (create transaction, etc) will be delegated to use of an external wallet tool like those listed above.

**Comment by guydavis** [comment]
Closing as [Machinaris version 0.6.9](https://github.com/guydavis/machinaris/releases/tag/0.6.9) has now been released.
