### ISSUE TITLE
Unraid Wiki corrections

### ISSUE THREAD

**Issue by saladm2** [guydavis/machinaris#92]
A minor change but on the Wiki --> Unraid page, in the "Get docker-compose" section, you have written:

```
To get docker-compose persist (after reboot) in Unraid create a file here
/boot/config/bash_axtra.cfg
```

but it should be `/boot/config/bash_extra.cfg` . 'extra' is spelled incorrectly

Also, on the FAQ page, in the "Can I use two (or more) final destination directories to hold my plots?" section, following the 'Value' line in the Unraid 'Add Configuration' screenshot, the `/plots/RAID1:/plots/UA1` syntax is incorrect. This is the correct syntax for the `docker run` command, but not inside of Unraid. 

It should be `/plots/RAID1, /plots/UA1` instead. The addition of a `:` here creates a user share named `:`, which is an invalid character, and is very difficult to remove. 

Furthermore, this syntax actually maps _both_ `/plots/RAID1` and `/plots/UA1` directories to the same variable in container, `plots_dir` in this case. I believe that multiple destination paths should be added as individual container paths, as described in the "Can I use two (or more) temporary plotting directories?" section.

**Comment by guydavis** [comment]
Thanks, I've improved both sections of the wiki.  Great suggestions!
