### ISSUE TITLE
Add support for archiving.

### ISSUE THREAD

**Issue by iamchriswick** [guydavis/machinaris#93]
I'm currently using my own scrip for archiving, but I would like to see the archive function from Plotman implemented in Machinaris.

As it's stated in the [Plotman Wiki](https://github.com/ericaltendorf/plotman/wiki/Archiving); Users should either use archiving or provide their own plot distribution mechanism. **/path/to/plots** are not intended to be the final storage location for plots.

**Comment by guydavis** [comment]
Yes, while their [configuration file](https://github.com/ericaltendorf/plotman/blob/main/src/plotman/resources/plotman.yaml#L58) states Archiving is **optional**: 

![image](https://user-images.githubusercontent.com/12936/121351806-64dbe580-c8e9-11eb-907b-a175dd069c42.png)

some of their recent [Issue discussions]( https://github.com/ericaltendorf/plotman/issues/671) seem to indicate they are about to make it mandatory.

Machinaris [does support archiving](https://github.com/guydavis/machinaris/wiki/Plotman#archiving) via Plotman over rsync.  I am running this myself, with two Windows plotters rsyncing over plots to an Unraid server. 

That said, this Plotman archiving support could be improved in Machinaris.  There is an [existing Issue](https://github.com/guydavis/machinaris/issues/88) for that improvement so please add your comments/suggestions there.
