### ISSUE TITLE
Disk usage graph not reporting correctly

### ISSUE THREAD

**Issue by chris-merritt** [guydavis/machinaris#938]
When viewing in transfer status or worker screen with many drives there is an issue with the graph.  I believe the 
"For legibility, the chart shows only a random selection of paths when a worker has many of them."  is changing the path names at the bottom but not updating the chart. The bars are just showing the 1st 20 drives not aligning with the labels at the bottom

What is shown in web ui
![image](https://github.com/guydavis/machinaris/assets/135200846/d3e6ec58-21be-4bec-a6f5-9482df3544a8)

Output from in container df -h
![image](https://github.com/guydavis/machinaris/assets/135200846/d91a4119-f272-4ff6-bf5c-04a7fdf0c1a6)

**Comment by guydavis** [comment]
Confirmed, I've reverted to showing the first X number of paths ensuring path aligns with correct used/free value.  Thanks for the report.  Available in the `machinaris:develop` image now.

**Comment by guydavis** [comment]
Released in Machinaris v2.1.2
