### ISSUE TITLE
Remove gigahorse dependency from chia node server

### ISSUE THREAD

**Issue by efnats** [guydavis/machinaris#944]
The gigahorse node is currently dependend on the machinaris chianode server running as a controller host.
This makes running two chia fullnodes a requirement to use gigahorse compressed plots including twice the network bandwith and disk usage.

With currently 35% of the entire netspace being gigahorse compressed, there is some justification to remove that dependency entirely.
Please consider releasing a version with node_gigahorse as the only controller host.

**Comment by guydavis** [comment]
Please see the [wiki](https://github.com/guydavis/machinaris/wiki/Gigahorse#why-do-i-need-a-chia-fullnode-too).

**Comment by efnats** [comment]
https://github.com/Chia-Network/chips/pull/88 is a proposal to have proprietary plot vendor software on harvesters communicate with the standard chia farmer.
After all, this may be the solution.
