### ISSUE TITLE
Machinaris-Chives: start as full node for masternode staking

### ISSUE THREAD

**Issue by efkay1** [guydavis/machinaris#975]
Hi,

I'm running a chives masternode with machinaris. to make this work the /chives-blockchain/chives/Masternode/start_masternode.py main function has to be set from:
```
def main():
    try:
        config = load_config_cli(DEFAULT_ROOT_PATH, "config.yaml", "seeder")
```

```
def main():
    try:
        config = load_config_cli(DEFAULT_ROOT_PATH, "config.yaml", "full_node")
```

otherwise the masternode won't come online. I have to do this every time the container restarts. Would be nice to implement, thank you!

**Describe the bug**
start_masternode.py script misconfigured by default

**To Reproduce**

1. chives start masternode
2. chives wallet masternode_mynode
3. Masternode wont come online

**Expected behavior**
masternode should start even when container gets restarted

**System setup:**
 - OS: Debian/OMV6
 - Docker latest
 - Machinaris branch: main
 - Machinaris version number latest

**Comment by guydavis** [comment]
Please direct concerns with the Chives code base to [their Github repo](https://github.com/HiveProject2021/chives-blockchain).  I simply bundle their release.
