### ISSUE TITLE
https://pool.space/

### ISSUE THREAD

**Issue by dylansproule** [guydavis/machinaris#994]
**Describe the bug**
When accessing my pool.space account I am now receiving: This account will not be receiving some or all of its rewards due to farming on at least one outdated Chia client, [learn more](https://docs.chia.net/consensus-forks/)

**To Reproduce**
Access your connected pool.space account

**System setup:**
 - OS:Ubuntu
 - Docker version: 27.1.1
 - Machinaris branch: latest
 - Machinaris 2.1.0

**Setup:**
docker compose stop
docker compose rm -f
docker compose pull && docker compose up -d --force-recreate

**Comment by guydavis** [comment]
The most recent version of Machinaris is [2.4.1](https://github.com/guydavis/machinaris/releases/tag/2.4.1) from a month ago.  It looks like you have an old image for some reason.  The pull should get the latest, so I don't know why its not.  Recommend you force the image deletion `stop` and `rm -f` before `up`.
